export const WTA_TOURNAMENTS = [
  // ── GRAND SLAMS ──────────────────────────────────────────────────────────────
  // Australian Open
  { year:2000, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Lindsay Davenport', runner_up:'Martina Hingis', winner_nationality:'USA', runner_up_nationality:'SUI', score:'6-1 7-5' },
  { year:2001, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Jennifer Capriati', runner_up:'Martina Hingis', winner_nationality:'USA', runner_up_nationality:'SUI', score:'6-4 6-3' },
  { year:2002, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Jennifer Capriati', runner_up:'Martina Hingis', winner_nationality:'USA', runner_up_nationality:'SUI', score:'4-6 7-6 6-2' },
  { year:2003, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Venus Williams', winner_nationality:'USA', runner_up_nationality:'USA', score:'7-6 3-6 6-4' },
  { year:2004, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Kim Clijsters', winner_nationality:'BEL', runner_up_nationality:'BEL', score:'6-3 4-6 6-3' },
  { year:2005, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Lindsay Davenport', winner_nationality:'USA', runner_up_nationality:'USA', score:'2-6 7-5 8-6' },
  { year:2006, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Amelie Mauresmo', runner_up:'Justine Henin', winner_nationality:'FRA', runner_up_nationality:'BEL', score:'6-1 2-0 ret.' },
  { year:2007, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Maria Sharapova', winner_nationality:'USA', runner_up_nationality:'RUS', score:'6-1 6-2' },
  { year:2008, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Maria Sharapova', runner_up:'Ana Ivanovic', winner_nationality:'RUS', runner_up_nationality:'SRB', score:'7-5 6-3' },
  { year:2009, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Dinara Safina', winner_nationality:'USA', runner_up_nationality:'RUS', score:'6-0 6-3' },
  { year:2010, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Justine Henin', winner_nationality:'USA', runner_up_nationality:'BEL', score:'6-4 3-6 6-2' },
  { year:2011, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Kim Clijsters', runner_up:'Li Na', winner_nationality:'BEL', runner_up_nationality:'CHN', score:'3-6 6-3 6-3' },
  { year:2012, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Victoria Azarenka', runner_up:'Maria Sharapova', winner_nationality:'BLR', runner_up_nationality:'RUS', score:'6-3 6-0' },
  { year:2013, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Victoria Azarenka', runner_up:'Li Na', winner_nationality:'BLR', runner_up_nationality:'CHN', score:'4-6 6-4 6-3' },
  { year:2014, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Li Na', runner_up:'Dominika Cibulkova', winner_nationality:'CHN', runner_up_nationality:'SVK', score:'7-6 6-0' },
  { year:2015, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Maria Sharapova', winner_nationality:'USA', runner_up_nationality:'RUS', score:'6-3 7-6' },
  { year:2016, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Angelique Kerber', runner_up:'Serena Williams', winner_nationality:'GER', runner_up_nationality:'USA', score:'6-4 3-6 6-4' },
  { year:2017, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Venus Williams', winner_nationality:'USA', runner_up_nationality:'USA', score:'6-4 6-4' },
  { year:2018, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Caroline Wozniacki', runner_up:'Simona Halep', winner_nationality:'DEN', runner_up_nationality:'ROU', score:'7-6 3-6 6-4' },
  { year:2019, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Naomi Osaka', runner_up:'Petra Kvitova', winner_nationality:'JPN', runner_up_nationality:'CZE', score:'7-6 5-7 6-4' },
  { year:2020, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Sofia Kenin', runner_up:'Garbine Muguruza', winner_nationality:'USA', runner_up_nationality:'ESP', score:'4-6 6-2 6-2' },
  { year:2021, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Naomi Osaka', runner_up:'Jennifer Brady', winner_nationality:'JPN', runner_up_nationality:'USA', score:'6-4 6-3' },
  { year:2022, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Ashleigh Barty', runner_up:'Danielle Collins', winner_nationality:'AUS', runner_up_nationality:'USA', score:'6-3 7-6' },
  { year:2023, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Aryna Sabalenka', runner_up:'Elena Rybakina', winner_nationality:'BLR', runner_up_nationality:'KAZ', score:'4-6 6-3 6-4' },
  { year:2024, name:'Australian Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Aryna Sabalenka', runner_up:'Qinwen Zheng', winner_nationality:'BLR', runner_up_nationality:'CHN', score:'6-3 6-2' },
  // Roland Garros
  { year:2000, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Mary Pierce', runner_up:'Conchita Martinez', winner_nationality:'FRA', runner_up_nationality:'ESP', score:'6-2 7-5' },
  { year:2001, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Jennifer Capriati', runner_up:'Kim Clijsters', winner_nationality:'USA', runner_up_nationality:'BEL', score:'1-6 6-4 12-10' },
  { year:2002, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Venus Williams', winner_nationality:'USA', runner_up_nationality:'USA', score:'7-5 6-3' },
  { year:2003, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Justine Henin', runner_up:'Kim Clijsters', winner_nationality:'BEL', runner_up_nationality:'BEL', score:'6-0 6-4' },
  { year:2004, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Anastasia Myskina', runner_up:'Elena Dementieva', winner_nationality:'RUS', runner_up_nationality:'RUS', score:'6-1 6-2' },
  { year:2005, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Justine Henin', runner_up:'Mary Pierce', winner_nationality:'BEL', runner_up_nationality:'FRA', score:'6-1 6-1' },
  { year:2006, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Justine Henin', runner_up:'Svetlana Kuznetsova', winner_nationality:'BEL', runner_up_nationality:'RUS', score:'6-4 6-4' },
  { year:2007, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Justine Henin', runner_up:'Ana Ivanovic', winner_nationality:'BEL', runner_up_nationality:'SRB', score:'6-1 6-2' },
  { year:2008, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Ana Ivanovic', runner_up:'Dinara Safina', winner_nationality:'SRB', runner_up_nationality:'RUS', score:'6-4 6-3' },
  { year:2009, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Svetlana Kuznetsova', runner_up:'Dinara Safina', winner_nationality:'RUS', runner_up_nationality:'RUS', score:'6-4 6-2' },
  { year:2010, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Francesca Schiavone', runner_up:'Samantha Stosur', winner_nationality:'ITA', runner_up_nationality:'AUS', score:'6-4 7-6' },
  { year:2011, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Li Na', runner_up:'Francesca Schiavone', winner_nationality:'CHN', runner_up_nationality:'ITA', score:'6-4 7-6' },
  { year:2012, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Maria Sharapova', runner_up:'Sara Errani', winner_nationality:'RUS', runner_up_nationality:'ITA', score:'6-3 6-2' },
  { year:2013, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Maria Sharapova', winner_nationality:'USA', runner_up_nationality:'RUS', score:'6-4 6-4' },
  { year:2014, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Maria Sharapova', runner_up:'Simona Halep', winner_nationality:'RUS', runner_up_nationality:'ROU', score:'6-4 6-7 6-4' },
  { year:2015, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Lucie Safarova', winner_nationality:'USA', runner_up_nationality:'CZE', score:'6-3 6-7 6-2' },
  { year:2016, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Garbine Muguruza', runner_up:'Serena Williams', winner_nationality:'ESP', runner_up_nationality:'USA', score:'7-5 6-4' },
  { year:2017, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Jelena Ostapenko', runner_up:'Simona Halep', winner_nationality:'LAT', runner_up_nationality:'ROU', score:'4-6 6-4 6-3' },
  { year:2018, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Simona Halep', runner_up:'Sloane Stephens', winner_nationality:'ROU', runner_up_nationality:'USA', score:'3-6 6-4 6-1' },
  { year:2019, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Ashleigh Barty', runner_up:'Marketa Vondrousova', winner_nationality:'AUS', runner_up_nationality:'CZE', score:'6-1 6-3' },
  { year:2020, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Iga Swiatek', runner_up:'Sofia Kenin', winner_nationality:'POL', runner_up_nationality:'USA', score:'6-4 6-1' },
  { year:2021, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Barbora Krejcikova', runner_up:'Anastasia Pavlyuchenkova', winner_nationality:'CZE', runner_up_nationality:'RUS', score:'6-1 2-6 6-4' },
  { year:2022, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Iga Swiatek', runner_up:'Coco Gauff', winner_nationality:'POL', runner_up_nationality:'USA', score:'6-1 6-3' },
  { year:2023, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Iga Swiatek', runner_up:'Karolina Muchova', winner_nationality:'POL', runner_up_nationality:'CZE', score:'6-2 5-7 6-4' },
  { year:2024, name:'Roland Garros', category:'Grand Slam', surface:'Clay', tour:'WTA', winner:'Iga Swiatek', runner_up:'Jasmine Paolini', winner_nationality:'POL', runner_up_nationality:'ITA', score:'6-2 6-1' },
  // Wimbledon
  { year:2000, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Venus Williams', runner_up:'Lindsay Davenport', winner_nationality:'USA', runner_up_nationality:'USA', score:'6-3 7-6' },
  { year:2001, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Venus Williams', runner_up:'Justine Henin', winner_nationality:'USA', runner_up_nationality:'BEL', score:'6-1 3-6 6-0' },
  { year:2002, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Serena Williams', runner_up:'Venus Williams', winner_nationality:'USA', runner_up_nationality:'USA', score:'7-6 6-3' },
  { year:2003, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Serena Williams', runner_up:'Venus Williams', winner_nationality:'USA', runner_up_nationality:'USA', score:'4-6 6-4 6-2' },
  { year:2004, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Maria Sharapova', runner_up:'Serena Williams', winner_nationality:'RUS', runner_up_nationality:'USA', score:'6-1 6-4' },
  { year:2005, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Venus Williams', runner_up:'Lindsay Davenport', winner_nationality:'USA', runner_up_nationality:'USA', score:'4-6 7-6 9-7' },
  { year:2006, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Amelie Mauresmo', runner_up:'Justine Henin', winner_nationality:'FRA', runner_up_nationality:'BEL', score:'2-6 6-3 6-4' },
  { year:2007, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Venus Williams', runner_up:'Marion Bartoli', winner_nationality:'USA', runner_up_nationality:'FRA', score:'6-4 6-1' },
  { year:2008, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Venus Williams', runner_up:'Serena Williams', winner_nationality:'USA', runner_up_nationality:'USA', score:'7-5 6-4' },
  { year:2009, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Serena Williams', runner_up:'Venus Williams', winner_nationality:'USA', runner_up_nationality:'USA', score:'7-6 6-2' },
  { year:2010, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Serena Williams', runner_up:'Vera Zvonareva', winner_nationality:'USA', runner_up_nationality:'RUS', score:'6-3 6-2' },
  { year:2011, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Petra Kvitova', runner_up:'Maria Sharapova', winner_nationality:'CZE', runner_up_nationality:'RUS', score:'6-3 6-4' },
  { year:2012, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Serena Williams', runner_up:'Agnieszka Radwanska', winner_nationality:'USA', runner_up_nationality:'POL', score:'6-1 5-7 6-2' },
  { year:2013, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Marion Bartoli', runner_up:'Sabine Lisicki', winner_nationality:'FRA', runner_up_nationality:'GER', score:'6-1 6-4' },
  { year:2014, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Petra Kvitova', runner_up:'Eugenie Bouchard', winner_nationality:'CZE', runner_up_nationality:'CAN', score:'6-3 6-0' },
  { year:2015, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Serena Williams', runner_up:'Garbine Muguruza', winner_nationality:'USA', runner_up_nationality:'ESP', score:'6-4 6-4' },
  { year:2016, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Serena Williams', runner_up:'Angelique Kerber', winner_nationality:'USA', runner_up_nationality:'GER', score:'7-5 6-3' },
  { year:2017, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Garbine Muguruza', runner_up:'Venus Williams', winner_nationality:'ESP', runner_up_nationality:'USA', score:'7-5 6-0' },
  { year:2018, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Angelique Kerber', runner_up:'Serena Williams', winner_nationality:'GER', runner_up_nationality:'USA', score:'6-3 6-3' },
  { year:2019, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Simona Halep', runner_up:'Serena Williams', winner_nationality:'ROU', runner_up_nationality:'USA', score:'6-2 6-2' },
  { year:2020, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'N/A (cancelled)', runner_up:'N/A', winner_nationality:'', runner_up_nationality:'' },
  { year:2021, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Ashleigh Barty', runner_up:'Karolina Pliskova', winner_nationality:'AUS', runner_up_nationality:'CZE', score:'6-3 6-7 6-3' },
  { year:2022, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Elena Rybakina', runner_up:'Ons Jabeur', winner_nationality:'KAZ', runner_up_nationality:'TUN', score:'3-6 6-2 6-2' },
  { year:2023, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Marketa Vondrousova', runner_up:'Ons Jabeur', winner_nationality:'CZE', runner_up_nationality:'TUN', score:'6-4 6-4' },
  { year:2024, name:'Wimbledon', category:'Grand Slam', surface:'Grass', tour:'WTA', winner:'Barbora Krejcikova', runner_up:'Jasmine Paolini', winner_nationality:'CZE', runner_up_nationality:'ITA', score:'6-2 2-6 6-4' },
  // US Open
  { year:2000, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Venus Williams', runner_up:'Lindsay Davenport', winner_nationality:'USA', runner_up_nationality:'USA', score:'6-4 7-5' },
  { year:2001, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Venus Williams', runner_up:'Serena Williams', winner_nationality:'USA', runner_up_nationality:'USA', score:'6-2 6-4' },
  { year:2002, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Venus Williams', winner_nationality:'USA', runner_up_nationality:'USA', score:'6-4 6-3' },
  { year:2003, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Kim Clijsters', winner_nationality:'BEL', runner_up_nationality:'BEL', score:'7-5 6-1' },
  { year:2004, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Svetlana Kuznetsova', runner_up:'Elena Dementieva', winner_nationality:'RUS', runner_up_nationality:'RUS', score:'6-3 7-5' },
  { year:2005, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Kim Clijsters', runner_up:'Mary Pierce', winner_nationality:'BEL', runner_up_nationality:'FRA', score:'6-3 6-1' },
  { year:2006, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Maria Sharapova', runner_up:'Justine Henin', winner_nationality:'RUS', runner_up_nationality:'BEL', score:'6-4 6-4' },
  { year:2007, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Svetlana Kuznetsova', winner_nationality:'BEL', runner_up_nationality:'RUS', score:'6-1 6-3' },
  { year:2008, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Jelena Jankovic', winner_nationality:'USA', runner_up_nationality:'SRB', score:'6-4 7-5' },
  { year:2009, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Kim Clijsters', runner_up:'Caroline Wozniacki', winner_nationality:'BEL', runner_up_nationality:'DEN', score:'7-5 6-3' },
  { year:2010, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Kim Clijsters', runner_up:'Vera Zvonareva', winner_nationality:'BEL', runner_up_nationality:'RUS', score:'6-2 6-1' },
  { year:2011, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Samantha Stosur', runner_up:'Serena Williams', winner_nationality:'AUS', runner_up_nationality:'USA', score:'6-2 6-3' },
  { year:2012, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Victoria Azarenka', winner_nationality:'USA', runner_up_nationality:'BLR', score:'6-2 2-6 7-5' },
  { year:2013, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Victoria Azarenka', winner_nationality:'USA', runner_up_nationality:'BLR', score:'7-5 6-7 6-1' },
  { year:2014, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Caroline Wozniacki', winner_nationality:'USA', runner_up_nationality:'DEN', score:'6-3 6-3' },
  { year:2015, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Flavia Pennetta', runner_up:'Roberta Vinci', winner_nationality:'ITA', runner_up_nationality:'ITA', score:'7-6 6-2' },
  { year:2016, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Angelique Kerber', runner_up:'Karolina Pliskova', winner_nationality:'GER', runner_up_nationality:'CZE', score:'6-3 4-6 6-4' },
  { year:2017, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Sloane Stephens', runner_up:'Madison Keys', winner_nationality:'USA', runner_up_nationality:'USA', score:'6-3 6-0' },
  { year:2018, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Naomi Osaka', runner_up:'Serena Williams', winner_nationality:'JPN', runner_up_nationality:'USA', score:'6-2 6-4' },
  { year:2019, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Bianca Andreescu', runner_up:'Serena Williams', winner_nationality:'CAN', runner_up_nationality:'USA', score:'6-3 7-5' },
  { year:2020, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Naomi Osaka', runner_up:'Victoria Azarenka', winner_nationality:'JPN', runner_up_nationality:'BLR', score:'1-6 6-3 6-3' },
  { year:2021, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Emma Raducanu', runner_up:'Belinda Bencic', winner_nationality:'GBR', runner_up_nationality:'SUI', score:'6-4 6-3' },
  { year:2022, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Iga Swiatek', runner_up:'Ons Jabeur', winner_nationality:'POL', runner_up_nationality:'TUN', score:'6-2 7-6' },
  { year:2023, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Coco Gauff', runner_up:'Aryna Sabalenka', winner_nationality:'USA', runner_up_nationality:'BLR', score:'2-6 6-3 6-2' },
  { year:2024, name:'US Open', category:'Grand Slam', surface:'Hard', tour:'WTA', winner:'Aryna Sabalenka', runner_up:'Jessica Pegula', winner_nationality:'BLR', runner_up_nationality:'USA', score:'7-5 7-5' },

  // ── WTA 1000 ─────────────────────────────────────────────────────────────────
  // Indian Wells
  { year:2000, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Martina Hingis', runner_up:'Lindsay Davenport', winner_nationality:'SUI', runner_up_nationality:'USA' },
  { year:2001, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Kim Clijsters', winner_nationality:'USA', runner_up_nationality:'BEL' },
  { year:2002, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Daniela Hantuchova', runner_up:'Martina Hingis', winner_nationality:'SVK', runner_up_nationality:'SUI' },
  { year:2003, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Kim Clijsters', runner_up:'Justine Henin', winner_nationality:'BEL', runner_up_nationality:'BEL' },
  { year:2004, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Elena Dementieva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2005, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Kim Clijsters', runner_up:'Maria Sharapova', winner_nationality:'BEL', runner_up_nationality:'RUS' },
  { year:2006, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Maria Sharapova', runner_up:'Svetlana Kuznetsova', winner_nationality:'RUS', runner_up_nationality:'RUS' },
  { year:2007, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Daniela Hantuchova', runner_up:'Svetlana Kuznetsova', winner_nationality:'SVK', runner_up_nationality:'RUS' },
  { year:2008, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Jelena Jankovic', winner_nationality:'USA', runner_up_nationality:'SRB' },
  { year:2009, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Victoria Azarenka', winner_nationality:'USA', runner_up_nationality:'BLR' },
  { year:2010, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Jelena Jankovic', runner_up:'Vera Zvonareva', winner_nationality:'SRB', runner_up_nationality:'RUS' },
  { year:2011, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Caroline Wozniacki', runner_up:'Jelena Jankovic', winner_nationality:'DEN', runner_up_nationality:'SRB' },
  { year:2012, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Victoria Azarenka', runner_up:'Maria Sharapova', winner_nationality:'BLR', runner_up_nationality:'RUS' },
  { year:2013, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Maria Sharapova', runner_up:'Caroline Wozniacki', winner_nationality:'RUS', runner_up_nationality:'DEN' },
  { year:2014, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Flavia Pennetta', runner_up:'Agnieszka Radwanska', winner_nationality:'ITA', runner_up_nationality:'POL' },
  { year:2015, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Simona Halep', runner_up:'Jelena Jankovic', winner_nationality:'ROU', runner_up_nationality:'SRB' },
  { year:2016, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Victoria Azarenka', runner_up:'Serena Williams', winner_nationality:'BLR', runner_up_nationality:'USA' },
  { year:2017, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Elena Vesnina', runner_up:'Elina Svitolina', winner_nationality:'RUS', runner_up_nationality:'UKR' },
  { year:2018, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Naomi Osaka', runner_up:'Daria Kasatkina', winner_nationality:'JPN', runner_up_nationality:'RUS' },
  { year:2019, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Bianca Andreescu', runner_up:'Angelique Kerber', winner_nationality:'CAN', runner_up_nationality:'GER' },
  { year:2020, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'N/A (cancelled)', runner_up:'N/A', winner_nationality:'', runner_up_nationality:'' },
  { year:2021, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Paula Badosa', runner_up:'Victoria Azarenka', winner_nationality:'ESP', runner_up_nationality:'BLR' },
  { year:2022, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Iga Swiatek', runner_up:'Simona Halep', winner_nationality:'POL', runner_up_nationality:'ROU' },
  { year:2023, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Elena Rybakina', runner_up:'Aryna Sabalenka', winner_nationality:'KAZ', runner_up_nationality:'BLR' },
  { year:2024, name:'Indian Wells', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Iga Swiatek', runner_up:'Maria Sakkari', winner_nationality:'POL', runner_up_nationality:'GRE' },
  // Miami
  { year:2000, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Venus Williams', runner_up:'Martina Hingis', winner_nationality:'USA', runner_up_nationality:'SUI' },
  { year:2001, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Venus Williams', runner_up:'Jennifer Capriati', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2002, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Jennifer Capriati', runner_up:'Serena Williams', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2003, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Jennifer Capriati', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2004, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Elena Dementieva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2005, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Kim Clijsters', runner_up:'Maria Sharapova', winner_nationality:'BEL', runner_up_nationality:'RUS' },
  { year:2006, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Maria Sharapova', runner_up:'Elena Dementieva', winner_nationality:'RUS', runner_up_nationality:'RUS' },
  { year:2007, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Svetlana Kuznetsova', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2008, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Jelena Jankovic', winner_nationality:'USA', runner_up_nationality:'SRB' },
  { year:2009, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Venus Williams', runner_up:'Serena Williams', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2010, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Kim Clijsters', runner_up:'Caroline Wozniacki', winner_nationality:'BEL', runner_up_nationality:'DEN' },
  { year:2011, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Victoria Azarenka', runner_up:'Serena Williams', winner_nationality:'BLR', runner_up_nationality:'USA' },
  { year:2012, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Agnieszka Radwanska', runner_up:'Maria Sharapova', winner_nationality:'POL', runner_up_nationality:'RUS' },
  { year:2013, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Maria Sharapova', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2014, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Agnieszka Radwanska', winner_nationality:'USA', runner_up_nationality:'POL' },
  { year:2015, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Carla Suarez Navarro', winner_nationality:'USA', runner_up_nationality:'ESP' },
  { year:2016, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Venus Williams', runner_up:'Victoria Azarenka', winner_nationality:'USA', runner_up_nationality:'BLR' },
  { year:2017, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Caroline Wozniacki', runner_up:'Caroline Garcia', winner_nationality:'DEN', runner_up_nationality:'FRA' },
  { year:2018, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Sloane Stephens', runner_up:'Jelena Ostapenko', winner_nationality:'USA', runner_up_nationality:'LAT' },
  { year:2019, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Ashleigh Barty', runner_up:'Karolina Pliskova', winner_nationality:'AUS', runner_up_nationality:'CZE' },
  { year:2020, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'N/A (cancelled)', runner_up:'N/A', winner_nationality:'', runner_up_nationality:'' },
  { year:2021, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Ashleigh Barty', runner_up:'Bianca Andreescu', winner_nationality:'AUS', runner_up_nationality:'CAN' },
  { year:2022, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Iga Swiatek', runner_up:'Naomi Osaka', winner_nationality:'POL', runner_up_nationality:'JPN' },
  { year:2023, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Iga Swiatek', runner_up:'Petra Kvitova', winner_nationality:'POL', runner_up_nationality:'CZE' },
  { year:2024, name:'Miami Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Iga Swiatek', runner_up:'Danielle Collins', winner_nationality:'POL', runner_up_nationality:'USA' },
  // German Open Berlin (2000-2008)
  { year:2000, name:'German Open Berlin', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Mary Pierce', runner_up:'Conchita Martinez', winner_nationality:'FRA', runner_up_nationality:'ESP' },
  { year:2001, name:'German Open Berlin', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Lindsay Davenport', runner_up:'Jennifer Capriati', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2002, name:'German Open Berlin', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Venus Williams', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2003, name:'German Open Berlin', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Justine Henin', runner_up:'Kim Clijsters', winner_nationality:'BEL', runner_up_nationality:'BEL' },
  { year:2004, name:'German Open Berlin', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Anastasia Myskina', runner_up:'Elena Dementieva', winner_nationality:'RUS', runner_up_nationality:'RUS' },
  { year:2005, name:'German Open Berlin', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Justine Henin', runner_up:'Svetlana Kuznetsova', winner_nationality:'BEL', runner_up_nationality:'RUS' },
  { year:2006, name:'German Open Berlin', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Justine Henin', runner_up:'Svetlana Kuznetsova', winner_nationality:'BEL', runner_up_nationality:'RUS' },
  { year:2007, name:'German Open Berlin', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Justine Henin', runner_up:'Ana Ivanovic', winner_nationality:'BEL', runner_up_nationality:'SRB' },
  { year:2008, name:'German Open Berlin', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Ana Ivanovic', runner_up:'Dinara Safina', winner_nationality:'SRB', runner_up_nationality:'RUS' },
  // Madrid (WTA, from 2004)
  { year:2004, name:'Madrid Open', category:'WTA 1000', surface:'Hard (i)', tour:'WTA', winner:'Serena Williams', runner_up:'Kim Clijsters', winner_nationality:'USA', runner_up_nationality:'BEL' },
  { year:2005, name:'Madrid Open', category:'WTA 1000', surface:'Hard (i)', tour:'WTA', winner:'Maria Sharapova', runner_up:'Svetlana Kuznetsova', winner_nationality:'RUS', runner_up_nationality:'RUS' },
  { year:2006, name:'Madrid Open', category:'WTA 1000', surface:'Hard (i)', tour:'WTA', winner:'Justine Henin', runner_up:'Serena Williams', winner_nationality:'BEL', runner_up_nationality:'USA' },
  { year:2007, name:'Madrid Open', category:'WTA 1000', surface:'Hard (i)', tour:'WTA', winner:'Justine Henin', runner_up:'Maria Sharapova', winner_nationality:'BEL', runner_up_nationality:'RUS' },
  { year:2008, name:'Madrid Open', category:'WTA 1000', surface:'Hard (i)', tour:'WTA', winner:'Dinara Safina', runner_up:'Serena Williams', winner_nationality:'RUS', runner_up_nationality:'USA' },
  { year:2009, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Dinara Safina', runner_up:'Victoria Azarenka', winner_nationality:'RUS', runner_up_nationality:'BLR' },
  { year:2010, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Aravane Rezai', runner_up:'Venus Williams', winner_nationality:'FRA', runner_up_nationality:'USA' },
  { year:2011, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Maria Sharapova', runner_up:'Petra Kvitova', winner_nationality:'RUS', runner_up_nationality:'CZE' },
  { year:2012, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Maria Sharapova', runner_up:'Victoria Azarenka', winner_nationality:'RUS', runner_up_nationality:'BLR' },
  { year:2013, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Maria Sharapova', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2014, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Petra Kvitova', runner_up:'Simona Halep', winner_nationality:'CZE', runner_up_nationality:'ROU' },
  { year:2015, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Flavia Pennetta', runner_up:'Carla Suarez Navarro', winner_nationality:'ITA', runner_up_nationality:'ESP' },
  { year:2016, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Angelique Kerber', runner_up:'Simona Halep', winner_nationality:'GER', runner_up_nationality:'ROU' },
  { year:2017, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Simona Halep', runner_up:'Kristina Mladenovic', winner_nationality:'ROU', runner_up_nationality:'FRA' },
  { year:2018, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Petra Kvitova', runner_up:'Simona Halep', winner_nationality:'CZE', runner_up_nationality:'ROU' },
  { year:2019, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Kiki Bertens', runner_up:'Simona Halep', winner_nationality:'NED', runner_up_nationality:'ROU' },
  { year:2020, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'N/A (cancelled)', runner_up:'N/A', winner_nationality:'', runner_up_nationality:'' },
  { year:2021, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Aryna Sabalenka', runner_up:'Ashleigh Barty', winner_nationality:'BLR', runner_up_nationality:'AUS' },
  { year:2022, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Ons Jabeur', runner_up:'Caroline Garcia', winner_nationality:'TUN', runner_up_nationality:'FRA' },
  { year:2023, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Iga Swiatek', runner_up:'Aryna Sabalenka', winner_nationality:'POL', runner_up_nationality:'BLR' },
  { year:2024, name:'Madrid Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Iga Swiatek', runner_up:'Aryna Sabalenka', winner_nationality:'POL', runner_up_nationality:'BLR' },
  // Rome (Italian Open)
  { year:2000, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Arantxa Sanchez Vicario', winner_nationality:'USA', runner_up_nationality:'ESP' },
  { year:2001, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Jennifer Capriati', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2002, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Jennifer Capriati', runner_up:'Kim Clijsters', winner_nationality:'USA', runner_up_nationality:'BEL' },
  { year:2003, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Justine Henin', winner_nationality:'USA', runner_up_nationality:'BEL' },
  { year:2004, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Maria Sharapova', runner_up:'Elena Dementieva', winner_nationality:'RUS', runner_up_nationality:'RUS' },
  { year:2005, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Justine Henin', winner_nationality:'USA', runner_up_nationality:'BEL' },
  { year:2006, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Anastasia Myskina', runner_up:'Svetlana Kuznetsova', winner_nationality:'RUS', runner_up_nationality:'RUS' },
  { year:2007, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Justine Henin', runner_up:'Ana Ivanovic', winner_nationality:'BEL', runner_up_nationality:'SRB' },
  { year:2008, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Jelena Jankovic', winner_nationality:'USA', runner_up_nationality:'SRB' },
  { year:2009, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Dinara Safina', runner_up:'Svetlana Kuznetsova', winner_nationality:'RUS', runner_up_nationality:'RUS' },
  { year:2010, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Jelena Jankovic', runner_up:'Francesca Schiavone', winner_nationality:'SRB', runner_up_nationality:'ITA' },
  { year:2011, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Victoria Azarenka', winner_nationality:'USA', runner_up_nationality:'BLR' },
  { year:2012, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Maria Sharapova', runner_up:'Serena Williams', winner_nationality:'RUS', runner_up_nationality:'USA' },
  { year:2013, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Victoria Azarenka', winner_nationality:'USA', runner_up_nationality:'BLR' },
  { year:2014, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Maria Sharapova', runner_up:'Simona Halep', winner_nationality:'RUS', runner_up_nationality:'ROU' },
  { year:2015, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Maria Sharapova', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2016, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Karolina Pliskova', runner_up:'Elina Svitolina', winner_nationality:'CZE', runner_up_nationality:'UKR' },
  { year:2017, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Elina Svitolina', runner_up:'Simona Halep', winner_nationality:'UKR', runner_up_nationality:'ROU' },
  { year:2018, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Elina Svitolina', runner_up:'Karolina Pliskova', winner_nationality:'UKR', runner_up_nationality:'CZE' },
  { year:2019, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Karolina Pliskova', runner_up:'Johanna Konta', winner_nationality:'CZE', runner_up_nationality:'GBR' },
  { year:2020, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Simona Halep', runner_up:'Karolina Pliskova', winner_nationality:'ROU', runner_up_nationality:'CZE' },
  { year:2021, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Aryna Sabalenka', runner_up:'Karolina Pliskova', winner_nationality:'BLR', runner_up_nationality:'CZE' },
  { year:2022, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Iga Swiatek', runner_up:'Ons Jabeur', winner_nationality:'POL', runner_up_nationality:'TUN' },
  { year:2023, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Iga Swiatek', runner_up:'Anhelina Kalinina', winner_nationality:'POL', runner_up_nationality:'UKR' },
  { year:2024, name:'Italian Open', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Iga Swiatek', runner_up:'Elina Svitolina', winner_nationality:'POL', runner_up_nationality:'UKR' },
  // Rogers Cup / Canada
  { year:2000, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Lindsay Davenport', runner_up:'Martina Hingis', winner_nationality:'USA', runner_up_nationality:'SUI' },
  { year:2001, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Martina Hingis', runner_up:'Jennifer Capriati', winner_nationality:'SUI', runner_up_nationality:'USA' },
  { year:2002, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Venus Williams', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2003, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Kim Clijsters', winner_nationality:'BEL', runner_up_nationality:'BEL' },
  { year:2004, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Lindsay Davenport', runner_up:'Svetlana Kuznetsova', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2005, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Lindsay Davenport', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2006, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Elena Dementieva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2007, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Svetlana Kuznetsova', winner_nationality:'BEL', runner_up_nationality:'RUS' },
  { year:2008, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Jelena Jankovic', runner_up:'Caroline Wozniacki', winner_nationality:'SRB', runner_up_nationality:'DEN' },
  { year:2009, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Elena Dementieva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2010, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Elena Dementieva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2011, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Vera Zvonareva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2012, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Maria Sharapova', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2013, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Li Na', winner_nationality:'USA', runner_up_nationality:'CHN' },
  { year:2014, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Eugenie Bouchard', runner_up:'Agnieszka Radwanska', winner_nationality:'CAN', runner_up_nationality:'POL' },
  { year:2015, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Simona Halep', runner_up:'Agnieszka Radwanska', winner_nationality:'ROU', runner_up_nationality:'POL' },
  { year:2016, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Angelique Kerber', runner_up:'Agnieszka Radwanska', winner_nationality:'GER', runner_up_nationality:'POL' },
  { year:2017, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Elina Svitolina', runner_up:'Caroline Garcia', winner_nationality:'UKR', runner_up_nationality:'FRA' },
  { year:2018, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Petra Kvitova', runner_up:'Sloane Stephens', winner_nationality:'CZE', runner_up_nationality:'USA' },
  { year:2019, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Bianca Andreescu', runner_up:'Serena Williams', winner_nationality:'CAN', runner_up_nationality:'USA' },
  { year:2020, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'N/A (cancelled)', runner_up:'N/A', winner_nationality:'', runner_up_nationality:'' },
  { year:2021, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Camila Giorgi', runner_up:'Karolina Pliskova', winner_nationality:'ITA', runner_up_nationality:'CZE' },
  { year:2022, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Caroline Garcia', runner_up:'Petra Kvitova', winner_nationality:'FRA', runner_up_nationality:'CZE' },
  { year:2023, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Iga Swiatek', runner_up:'Jessica Pegula', winner_nationality:'POL', runner_up_nationality:'USA' },
  { year:2024, name:'Rogers Cup', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Aryna Sabalenka', runner_up:'Jessica Pegula', winner_nationality:'BLR', runner_up_nationality:'USA' },
  // Cincinnati (Western & Southern Open, WTA from 2004)
  { year:2004, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Lindsay Davenport', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2005, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Maria Sharapova', runner_up:'Kim Clijsters', winner_nationality:'RUS', runner_up_nationality:'BEL' },
  { year:2006, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Elena Dementieva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2007, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Victoria Azarenka', winner_nationality:'USA', runner_up_nationality:'BLR' },
  { year:2008, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Jelena Jankovic', runner_up:'Caroline Wozniacki', winner_nationality:'SRB', runner_up_nationality:'DEN' },
  { year:2009, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Jelena Jankovic', winner_nationality:'USA', runner_up_nationality:'SRB' },
  { year:2010, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Victoria Azarenka', runner_up:'Elena Dementieva', winner_nationality:'BLR', runner_up_nationality:'RUS' },
  { year:2011, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Maria Sharapova', runner_up:'Agnieszka Radwanska', winner_nationality:'RUS', runner_up_nationality:'POL' },
  { year:2012, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Victoria Azarenka', winner_nationality:'USA', runner_up_nationality:'BLR' },
  { year:2013, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Victoria Azarenka', winner_nationality:'USA', runner_up_nationality:'BLR' },
  { year:2014, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Simona Halep', winner_nationality:'USA', runner_up_nationality:'ROU' },
  { year:2015, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Simona Halep', winner_nationality:'USA', runner_up_nationality:'ROU' },
  { year:2016, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Karolina Pliskova', runner_up:'Angelique Kerber', winner_nationality:'CZE', runner_up_nationality:'GER' },
  { year:2017, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Garbine Muguruza', runner_up:'Simona Halep', winner_nationality:'ESP', runner_up_nationality:'ROU' },
  { year:2018, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Kiki Bertens', runner_up:'Simona Halep', winner_nationality:'NED', runner_up_nationality:'ROU' },
  { year:2019, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Madison Keys', runner_up:'Svetlana Kuznetsova', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2020, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Victoria Azarenka', runner_up:'Naomi Osaka', winner_nationality:'BLR', runner_up_nationality:'JPN' },
  { year:2021, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Jil Teichmann', runner_up:'Aryna Sabalenka', winner_nationality:'SUI', runner_up_nationality:'BLR' },
  { year:2022, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Caroline Garcia', runner_up:'Petra Kvitova', winner_nationality:'FRA', runner_up_nationality:'CZE' },
  { year:2023, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Coco Gauff', runner_up:'Karolina Muchova', winner_nationality:'USA', runner_up_nationality:'CZE' },
  { year:2024, name:'Cincinnati Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Jessica Pegula', runner_up:'Aryna Sabalenka', winner_nationality:'USA', runner_up_nationality:'BLR' },
  // Pan Pacific Open / Tokyo (2000-2011)
  { year:2000, name:'Pan Pacific Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Martina Hingis', runner_up:'Mary Pierce', winner_nationality:'SUI', runner_up_nationality:'FRA' },
  { year:2001, name:'Pan Pacific Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Lindsay Davenport', runner_up:'Martina Hingis', winner_nationality:'USA', runner_up_nationality:'SUI' },
  { year:2002, name:'Pan Pacific Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Jennifer Capriati', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2003, name:'Pan Pacific Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Kim Clijsters', runner_up:'Amelie Mauresmo', winner_nationality:'BEL', runner_up_nationality:'FRA' },
  { year:2004, name:'Pan Pacific Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Elena Dementieva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2005, name:'Pan Pacific Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Svetlana Kuznetsova', winner_nationality:'BEL', runner_up_nationality:'RUS' },
  { year:2006, name:'Pan Pacific Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Amelie Mauresmo', winner_nationality:'BEL', runner_up_nationality:'FRA' },
  { year:2007, name:'Pan Pacific Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Ana Ivanovic', winner_nationality:'BEL', runner_up_nationality:'SRB' },
  { year:2008, name:'Pan Pacific Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Jelena Jankovic', winner_nationality:'USA', runner_up_nationality:'SRB' },
  { year:2009, name:'Pan Pacific Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Vera Zvonareva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2010, name:'Pan Pacific Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Vera Zvonareva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2011, name:'Pan Pacific Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Caroline Wozniacki', winner_nationality:'USA', runner_up_nationality:'DEN' },
  // China Open / Beijing (2004-2019)
  { year:2004, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Svetlana Kuznetsova', winner_nationality:'BEL', runner_up_nationality:'RUS' },
  { year:2005, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Nathalie Dechy', runner_up:'Svetlana Kuznetsova', winner_nationality:'FRA', runner_up_nationality:'RUS' },
  { year:2006, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Maria Sharapova', runner_up:'Svetlana Kuznetsova', winner_nationality:'RUS', runner_up_nationality:'RUS' },
  { year:2007, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Jelena Jankovic', runner_up:'Anna Chakvetadze', winner_nationality:'SRB', runner_up_nationality:'RUS' },
  { year:2008, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Jelena Jankovic', winner_nationality:'USA', runner_up_nationality:'SRB' },
  { year:2009, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Caroline Wozniacki', winner_nationality:'USA', runner_up_nationality:'DEN' },
  { year:2010, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Caroline Wozniacki', winner_nationality:'USA', runner_up_nationality:'DEN' },
  { year:2011, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Caroline Wozniacki', runner_up:'Agnieszka Radwanska', winner_nationality:'DEN', runner_up_nationality:'POL' },
  { year:2012, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Maria Sharapova', runner_up:'Agnieszka Radwanska', winner_nationality:'RUS', runner_up_nationality:'POL' },
  { year:2013, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Maria Sharapova', runner_up:'Jelena Jankovic', winner_nationality:'RUS', runner_up_nationality:'SRB' },
  { year:2014, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Maria Sharapova', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2015, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Agnieszka Radwanska', winner_nationality:'USA', runner_up_nationality:'POL' },
  { year:2016, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Agnieszka Radwanska', runner_up:'Simona Halep', winner_nationality:'POL', runner_up_nationality:'ROU' },
  { year:2017, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Garbine Muguruza', runner_up:'Caroline Garcia', winner_nationality:'ESP', runner_up_nationality:'FRA' },
  { year:2018, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Naomi Osaka', runner_up:'Petra Kvitova', winner_nationality:'JPN', runner_up_nationality:'CZE' },
  { year:2019, name:'China Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Naomi Osaka', runner_up:'Ashleigh Barty', winner_nationality:'JPN', runner_up_nationality:'AUS' },
  // Wuhan Open (2014-2019)
  { year:2014, name:'Wuhan Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Petra Kvitova', runner_up:'Agnieszka Radwanska', winner_nationality:'CZE', runner_up_nationality:'POL' },
  { year:2015, name:'Wuhan Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Garbine Muguruza', runner_up:'Simona Halep', winner_nationality:'ESP', runner_up_nationality:'ROU' },
  { year:2016, name:'Wuhan Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Agnieszka Radwanska', runner_up:'Petra Kvitova', winner_nationality:'POL', runner_up_nationality:'CZE' },
  { year:2017, name:'Wuhan Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Kiki Bertens', runner_up:'Elina Svitolina', winner_nationality:'NED', runner_up_nationality:'UKR' },
  { year:2018, name:'Wuhan Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Aryna Sabalenka', runner_up:'Agnieszka Radwanska', winner_nationality:'BLR', runner_up_nationality:'POL' },
  { year:2019, name:'Wuhan Open', category:'WTA 1000', surface:'Hard', tour:'WTA', winner:'Elina Svitolina', runner_up:'Petra Kvitova', winner_nationality:'UKR', runner_up_nationality:'CZE' },
  // Stuttgart Porsche Grand Prix
  { year:2006, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Justine Henin', runner_up:'Maria Sharapova', winner_nationality:'BEL', runner_up_nationality:'RUS' },
  { year:2007, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Jelena Jankovic', winner_nationality:'USA', runner_up_nationality:'SRB' },
  { year:2008, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Dinara Safina', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2009, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Ana Ivanovic', runner_up:'Vera Zvonareva', winner_nationality:'SRB', runner_up_nationality:'RUS' },
  { year:2010, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Samantha Stosur', winner_nationality:'USA', runner_up_nationality:'AUS' },
  { year:2011, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Maria Sharapova', runner_up:'Petra Kvitova', winner_nationality:'RUS', runner_up_nationality:'CZE' },
  { year:2012, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Maria Sharapova', runner_up:'Victoria Azarenka', winner_nationality:'RUS', runner_up_nationality:'BLR' },
  { year:2013, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Maria Sharapova', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2014, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Maria Sharapova', runner_up:'Simona Halep', winner_nationality:'RUS', runner_up_nationality:'ROU' },
  { year:2015, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Maria Sharapova', runner_up:'Lucie Safarova', winner_nationality:'RUS', runner_up_nationality:'CZE' },
  { year:2016, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Angelique Kerber', runner_up:'Laura Siegemund', winner_nationality:'GER', runner_up_nationality:'GER' },
  { year:2017, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Laura Siegemund', runner_up:'Kristina Mladenovic', winner_nationality:'GER', runner_up_nationality:'FRA' },
  { year:2018, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Karolina Pliskova', runner_up:'Petra Kvitova', winner_nationality:'CZE', runner_up_nationality:'CZE' },
  { year:2019, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Petra Kvitova', runner_up:'Kiki Bertens', winner_nationality:'CZE', runner_up_nationality:'NED' },
  { year:2020, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'N/A (cancelled)', runner_up:'N/A', winner_nationality:'', runner_up_nationality:'' },
  { year:2021, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Ashleigh Barty', runner_up:'Aryna Sabalenka', winner_nationality:'AUS', runner_up_nationality:'BLR' },
  { year:2022, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Iga Swiatek', runner_up:'Aryna Sabalenka', winner_nationality:'POL', runner_up_nationality:'BLR' },
  { year:2023, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Aryna Sabalenka', runner_up:'Iga Swiatek', winner_nationality:'BLR', runner_up_nationality:'POL' },
  { year:2024, name:'Porsche Grand Prix Stuttgart', category:'WTA 1000', surface:'Clay', tour:'WTA', winner:'Iga Swiatek', runner_up:'Elena Rybakina', winner_nationality:'POL', runner_up_nationality:'KAZ' },

  // ── WTA 500 ──────────────────────────────────────────────────────────────────
  // Dubai
  { year:2001, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Martina Hingis', runner_up:'Lindsay Davenport', winner_nationality:'SUI', runner_up_nationality:'USA' },
  { year:2002, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Jennifer Capriati', runner_up:'Justine Henin', winner_nationality:'USA', runner_up_nationality:'BEL' },
  { year:2003, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Amelie Mauresmo', runner_up:'Jennifer Capriati', winner_nationality:'FRA', runner_up_nationality:'USA' },
  { year:2004, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Kim Clijsters', runner_up:'Lindsay Davenport', winner_nationality:'BEL', runner_up_nationality:'USA' },
  { year:2005, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Maria Sharapova', winner_nationality:'BEL', runner_up_nationality:'RUS' },
  { year:2006, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Svetlana Kuznetsova', runner_up:'Justine Henin', winner_nationality:'RUS', runner_up_nationality:'BEL' },
  { year:2007, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Jelena Jankovic', winner_nationality:'BEL', runner_up_nationality:'SRB' },
  { year:2008, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Jelena Jankovic', runner_up:'Vera Zvonareva', winner_nationality:'SRB', runner_up_nationality:'RUS' },
  { year:2009, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Venus Williams', runner_up:'Elena Dementieva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2010, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Caroline Wozniacki', winner_nationality:'BEL', runner_up_nationality:'DEN' },
  { year:2011, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Vera Zvonareva', runner_up:'Caroline Wozniacki', winner_nationality:'RUS', runner_up_nationality:'DEN' },
  { year:2012, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Agnieszka Radwanska', runner_up:'Petra Kvitova', winner_nationality:'POL', runner_up_nationality:'CZE' },
  { year:2013, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Maria Sharapova', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2014, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Alize Cornet', winner_nationality:'USA', runner_up_nationality:'FRA' },
  { year:2015, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Flavia Pennetta', runner_up:'Simona Halep', winner_nationality:'ITA', runner_up_nationality:'ROU' },
  { year:2016, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Agnieszka Radwanska', runner_up:'Karolina Pliskova', winner_nationality:'POL', runner_up_nationality:'CZE' },
  { year:2017, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Elina Svitolina', runner_up:'Caroline Wozniacki', winner_nationality:'UKR', runner_up_nationality:'DEN' },
  { year:2018, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Elina Svitolina', runner_up:'Angelique Kerber', winner_nationality:'UKR', runner_up_nationality:'GER' },
  { year:2019, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Elina Svitolina', runner_up:'Petra Kvitova', winner_nationality:'UKR', runner_up_nationality:'CZE' },
  { year:2021, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Elina Svitolina', runner_up:'Petra Kvitova', winner_nationality:'UKR', runner_up_nationality:'CZE' },
  { year:2022, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Barbora Krejcikova', runner_up:'Anett Kontaveit', winner_nationality:'CZE', runner_up_nationality:'EST' },
  { year:2023, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Barbora Krejcikova', runner_up:'Iga Swiatek', winner_nationality:'CZE', runner_up_nationality:'POL' },
  { year:2024, name:'Dubai Tennis Championships', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Iga Swiatek', runner_up:'Jasmine Paolini', winner_nationality:'POL', runner_up_nationality:'ITA' },
  // Qatar Total Open / Doha
  { year:2001, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Lindsay Davenport', runner_up:'Martina Hingis', winner_nationality:'USA', runner_up_nationality:'SUI' },
  { year:2002, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Amelie Mauresmo', winner_nationality:'BEL', runner_up_nationality:'FRA' },
  { year:2003, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Kim Clijsters', winner_nationality:'BEL', runner_up_nationality:'BEL' },
  { year:2004, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Svetlana Kuznetsova', runner_up:'Elena Dementieva', winner_nationality:'RUS', runner_up_nationality:'RUS' },
  { year:2005, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Maria Sharapova', runner_up:'Svetlana Kuznetsova', winner_nationality:'RUS', runner_up_nationality:'RUS' },
  { year:2006, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Maria Sharapova', runner_up:'Elena Dementieva', winner_nationality:'RUS', runner_up_nationality:'RUS' },
  { year:2007, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Jelena Jankovic', runner_up:'Svetlana Kuznetsova', winner_nationality:'SRB', runner_up_nationality:'RUS' },
  { year:2008, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Dinara Safina', runner_up:'Jelena Jankovic', winner_nationality:'RUS', runner_up_nationality:'SRB' },
  { year:2009, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Elena Dementieva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2010, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Vera Zvonareva', runner_up:'Agnieszka Radwanska', winner_nationality:'RUS', runner_up_nationality:'POL' },
  { year:2011, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Vera Zvonareva', runner_up:'Victoria Azarenka', winner_nationality:'RUS', runner_up_nationality:'BLR' },
  { year:2012, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Victoria Azarenka', runner_up:'Maria Sharapova', winner_nationality:'BLR', runner_up_nationality:'RUS' },
  { year:2013, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Victoria Azarenka', runner_up:'Maria Sharapova', winner_nationality:'BLR', runner_up_nationality:'RUS' },
  { year:2014, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Jelena Jankovic', winner_nationality:'USA', runner_up_nationality:'SRB' },
  { year:2015, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Simona Halep', winner_nationality:'USA', runner_up_nationality:'ROU' },
  { year:2016, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Angelique Kerber', runner_up:'Karolina Pliskova', winner_nationality:'GER', runner_up_nationality:'CZE' },
  { year:2017, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Elina Svitolina', runner_up:'Caroline Wozniacki', winner_nationality:'UKR', runner_up_nationality:'DEN' },
  { year:2018, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Petra Kvitova', runner_up:'Elina Svitolina', winner_nationality:'CZE', runner_up_nationality:'UKR' },
  { year:2019, name:'Qatar Total Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Simona Halep', runner_up:'Elina Svitolina', winner_nationality:'ROU', runner_up_nationality:'UKR' },
  // Charleston / Family Circle Cup
  { year:2000, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Lindsay Davenport', runner_up:'Martina Hingis', winner_nationality:'USA', runner_up_nationality:'SUI' },
  { year:2001, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Justine Henin', runner_up:'Kim Clijsters', winner_nationality:'BEL', runner_up_nationality:'BEL' },
  { year:2002, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Justine Henin', runner_up:'Jennifer Capriati', winner_nationality:'BEL', runner_up_nationality:'USA' },
  { year:2003, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Jennifer Capriati', runner_up:'Kim Clijsters', winner_nationality:'USA', runner_up_nationality:'BEL' },
  { year:2004, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Svetlana Kuznetsova', runner_up:'Maria Sharapova', winner_nationality:'RUS', runner_up_nationality:'RUS' },
  { year:2005, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Svetlana Kuznetsova', runner_up:'Justine Henin', winner_nationality:'RUS', runner_up_nationality:'BEL' },
  { year:2006, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Jelena Jankovic', winner_nationality:'USA', runner_up_nationality:'SRB' },
  { year:2007, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Maria Sharapova', runner_up:'Jelena Jankovic', winner_nationality:'RUS', runner_up_nationality:'SRB' },
  { year:2008, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Ana Ivanovic', runner_up:'Jelena Jankovic', winner_nationality:'SRB', runner_up_nationality:'SRB' },
  { year:2009, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Samantha Stosur', winner_nationality:'USA', runner_up_nationality:'AUS' },
  { year:2010, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Jelena Jankovic', winner_nationality:'USA', runner_up_nationality:'SRB' },
  { year:2011, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Maria Sharapova', runner_up:'Serena Williams', winner_nationality:'RUS', runner_up_nationality:'USA' },
  { year:2012, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Agnieszka Radwanska', winner_nationality:'USA', runner_up_nationality:'POL' },
  { year:2013, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Maria Sharapova', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2014, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Serena Williams', runner_up:'Simona Halep', winner_nationality:'USA', runner_up_nationality:'ROU' },
  { year:2015, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Lucie Safarova', runner_up:'Jelena Jankovic', winner_nationality:'CZE', runner_up_nationality:'SRB' },
  { year:2016, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Madison Keys', runner_up:'Serena Williams', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2017, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Sloane Stephens', runner_up:'Madison Keys', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2018, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Sloane Stephens', runner_up:'Daria Kasatkina', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2019, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Ashleigh Barty', runner_up:'Madison Keys', winner_nationality:'AUS', runner_up_nationality:'USA' },
  { year:2021, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Belinda Bencic', runner_up:'Jessica Pegula', winner_nationality:'SUI', runner_up_nationality:'USA' },
  { year:2022, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Ons Jabeur', runner_up:'Belinda Bencic', winner_nationality:'TUN', runner_up_nationality:'SUI' },
  { year:2023, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Madison Keys', runner_up:'Barbora Krejcikova', winner_nationality:'USA', runner_up_nationality:'CZE' },
  { year:2024, name:'Charleston Open', category:'WTA 500', surface:'Clay', tour:'WTA', winner:'Marketa Vondrousova', runner_up:'Elena Rybakina', winner_nationality:'CZE', runner_up_nationality:'KAZ' },
  // Stanford / Bank of the West Classic (2000-2019)
  { year:2000, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Lindsay Davenport', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2001, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Venus Williams', runner_up:'Serena Williams', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2002, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Venus Williams', runner_up:'Jennifer Capriati', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2003, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Kim Clijsters', winner_nationality:'BEL', runner_up_nationality:'BEL' },
  { year:2004, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Maria Sharapova', runner_up:'Lindsay Davenport', winner_nationality:'RUS', runner_up_nationality:'USA' },
  { year:2005, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Lindsay Davenport', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2006, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Maria Sharapova', runner_up:'Svetlana Kuznetsova', winner_nationality:'RUS', runner_up_nationality:'RUS' },
  { year:2007, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Jelena Jankovic', winner_nationality:'USA', runner_up_nationality:'SRB' },
  { year:2008, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Jelena Jankovic', winner_nationality:'USA', runner_up_nationality:'SRB' },
  { year:2009, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Venus Williams', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2010, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Victoria Azarenka', winner_nationality:'USA', runner_up_nationality:'BLR' },
  { year:2011, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Victoria Azarenka', winner_nationality:'USA', runner_up_nationality:'BLR' },
  { year:2012, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Maria Sharapova', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2013, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Sloane Stephens', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2014, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Simona Halep', runner_up:'Serena Williams', winner_nationality:'ROU', runner_up_nationality:'USA' },
  { year:2015, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Madison Keys', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2016, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Simona Halep', runner_up:'Madison Keys', winner_nationality:'ROU', runner_up_nationality:'USA' },
  { year:2017, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'CoCo Vandeweghe', runner_up:'Simona Halep', winner_nationality:'USA', runner_up_nationality:'ROU' },
  { year:2018, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Sloane Stephens', runner_up:'Madison Keys', winner_nationality:'USA', runner_up_nationality:'USA' },
  { year:2019, name:'Stanford Classic', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Bianca Andreescu', runner_up:'Serena Williams', winner_nationality:'CAN', runner_up_nationality:'USA' },
  // Connecticut / New Haven (2000-2018)
  { year:2000, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Martina Hingis', runner_up:'Venus Williams', winner_nationality:'SUI', runner_up_nationality:'USA' },
  { year:2001, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Martina Hingis', runner_up:'Jelena Dokic', winner_nationality:'SUI', runner_up_nationality:'AUS' },
  { year:2002, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Martina Hingis', runner_up:'Serena Williams', winner_nationality:'SUI', runner_up_nationality:'USA' },
  { year:2003, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Kim Clijsters', winner_nationality:'USA', runner_up_nationality:'BEL' },
  { year:2004, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Maria Sharapova', runner_up:'Elena Dementieva', winner_nationality:'RUS', runner_up_nationality:'RUS' },
  { year:2005, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Kim Clijsters', runner_up:'Dinara Safina', winner_nationality:'BEL', runner_up_nationality:'RUS' },
  { year:2006, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Jelena Jankovic', runner_up:'Svetlana Kuznetsova', winner_nationality:'SRB', runner_up_nationality:'RUS' },
  { year:2007, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Justine Henin', runner_up:'Serena Williams', winner_nationality:'BEL', runner_up_nationality:'USA' },
  { year:2008, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Jelena Jankovic', runner_up:'Caroline Wozniacki', winner_nationality:'SRB', runner_up_nationality:'DEN' },
  { year:2009, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Caroline Wozniacki', winner_nationality:'USA', runner_up_nationality:'DEN' },
  { year:2010, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Vera Zvonareva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2011, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Victoria Azarenka', runner_up:'Caroline Wozniacki', winner_nationality:'BLR', runner_up_nationality:'DEN' },
  { year:2012, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Caroline Wozniacki', runner_up:'Maria Sharapova', winner_nationality:'DEN', runner_up_nationality:'RUS' },
  { year:2013, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Victoria Azarenka', winner_nationality:'USA', runner_up_nationality:'BLR' },
  { year:2014, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Agnieszka Radwanska', winner_nationality:'USA', runner_up_nationality:'POL' },
  { year:2015, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Serena Williams', runner_up:'Simona Halep', winner_nationality:'USA', runner_up_nationality:'ROU' },
  { year:2016, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Agnieszka Radwanska', runner_up:'Simona Halep', winner_nationality:'POL', runner_up_nationality:'ROU' },
  { year:2017, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Karolina Pliskova', runner_up:'Jelena Ostapenko', winner_nationality:'CZE', runner_up_nationality:'LAT' },
  { year:2018, name:'Connecticut Open', category:'WTA 500', surface:'Hard', tour:'WTA', winner:'Lesia Tsurenko', runner_up:'Petra Kvitova', winner_nationality:'UKR', runner_up_nationality:'CZE' },
  // Eastbourne (2006-2024)
  { year:2006, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Serena Williams', runner_up:'Jelena Jankovic', winner_nationality:'USA', runner_up_nationality:'SRB' },
  { year:2007, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Serena Williams', runner_up:'Agnieszka Radwanska', winner_nationality:'USA', runner_up_nationality:'POL' },
  { year:2008, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Agnieszka Radwanska', runner_up:'Jelena Jankovic', winner_nationality:'POL', runner_up_nationality:'SRB' },
  { year:2009, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Serena Williams', runner_up:'Elena Dementieva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2010, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Serena Williams', runner_up:'Vera Zvonareva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2011, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Serena Williams', runner_up:'Vera Zvonareva', winner_nationality:'USA', runner_up_nationality:'RUS' },
  { year:2012, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Maria Sharapova', runner_up:'Serena Williams', winner_nationality:'RUS', runner_up_nationality:'USA' },
  { year:2013, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Serena Williams', runner_up:'Agnieszka Radwanska', winner_nationality:'USA', runner_up_nationality:'POL' },
  { year:2014, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Serena Williams', runner_up:'Petra Kvitova', winner_nationality:'USA', runner_up_nationality:'CZE' },
  { year:2015, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Karolina Pliskova', runner_up:'Agnieszka Radwanska', winner_nationality:'CZE', runner_up_nationality:'POL' },
  { year:2016, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Petra Kvitova', runner_up:'Madison Brengle', winner_nationality:'CZE', runner_up_nationality:'USA' },
  { year:2017, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Johanna Konta', runner_up:'Simona Halep', winner_nationality:'GBR', runner_up_nationality:'ROU' },
  { year:2018, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Karolina Pliskova', runner_up:'Elina Svitolina', winner_nationality:'CZE', runner_up_nationality:'UKR' },
  { year:2019, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Karolina Pliskova', runner_up:'Aryna Sabalenka', winner_nationality:'CZE', runner_up_nationality:'BLR' },
  { year:2021, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Karolina Pliskova', runner_up:'Ons Jabeur', winner_nationality:'CZE', runner_up_nationality:'TUN' },
  { year:2022, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Ons Jabeur', runner_up:'Maria Sakkari', winner_nationality:'TUN', runner_up_nationality:'GRE' },
  { year:2023, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Iga Swiatek', runner_up:'Petra Kvitova', winner_nationality:'POL', runner_up_nationality:'CZE' },
  { year:2024, name:'Eastbourne Classic', category:'WTA 500', surface:'Grass', tour:'WTA', winner:'Iga Swiatek', runner_up:'Daria Kasatkina', winner_nationality:'POL', runner_up_nationality:'RUS' },
];
