// Tennis tournament data 2000-2024
// Sources: ATP Tour official records, Wikipedia
export const TOURNAMENTS = [
  // ── 2000 ──────────────────────────────────────────────────────
  // Grand Slams
  { year: 2000, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Andre Agassi', runner_up: 'Yevgeny Kafelnikov', winner_nationality: 'USA', runner_up_nationality: 'RUS', score: '3-6 6-3 6-2 6-4' },
  { year: 2000, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Gustavo Kuerten', runner_up: 'Magnus Norman', winner_nationality: 'BRA', runner_up_nationality: 'SWE', score: '6-2 6-3 2-6 7-6' },
  { year: 2000, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Pete Sampras', runner_up: 'Patrick Rafter', winner_nationality: 'USA', runner_up_nationality: 'AUS', score: '6-7 7-6 6-4 6-2' },
  { year: 2000, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Marat Safin', runner_up: 'Pete Sampras', winner_nationality: 'RUS', runner_up_nationality: 'USA', score: '6-4 6-3 6-3' },
  // Masters 1000
  { year: 2000, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Lleyton Hewitt', runner_up: 'Yevgeny Kafelnikov', winner_nationality: 'AUS', runner_up_nationality: 'RUS' },
  { year: 2000, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Andre Agassi', runner_up: 'Magnus Norman', winner_nationality: 'USA', runner_up_nationality: 'SWE' },
  { year: 2000, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Cedric Pioline', runner_up: 'Gustavo Kuerten', winner_nationality: 'FRA', runner_up_nationality: 'BRA' },
  { year: 2000, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Gustavo Kuerten', runner_up: 'Franco Squillari', winner_nationality: 'BRA', runner_up_nationality: 'ARG' },
  { year: 2000, name: 'Hamburg', category: 'Masters 1000', surface: 'Clay', winner: 'Gustavo Kuerten', runner_up: 'Marc Rosset', winner_nationality: 'BRA', runner_up_nationality: 'SUI' },
  { year: 2000, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Thomas Enqvist', runner_up: 'Mark Philippoussis', winner_nationality: 'SWE', runner_up_nationality: 'AUS' },
  { year: 2000, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Pete Sampras', runner_up: 'Lleyton Hewitt', winner_nationality: 'USA', runner_up_nationality: 'AUS' },
  { year: 2000, name: 'Stuttgart', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Wayne Ferreira', runner_up: 'Lleyton Hewitt', winner_nationality: 'RSA', runner_up_nationality: 'AUS' },
  { year: 2000, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Marat Safin', runner_up: 'Jan-Michael Gambill', winner_nationality: 'RUS', runner_up_nationality: 'USA' },

  // ── 2001 ──────────────────────────────────────────────────────
  { year: 2001, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Andre Agassi', runner_up: 'Arnaud Clément', winner_nationality: 'USA', runner_up_nationality: 'FRA', score: '6-4 6-2 6-2' },
  { year: 2001, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Gustavo Kuerten', runner_up: 'Alex Corretja', winner_nationality: 'BRA', runner_up_nationality: 'ESP', score: '6-7 7-5 6-2 6-0' },
  { year: 2001, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Goran Ivanisevic', runner_up: 'Pat Rafter', winner_nationality: 'CRO', runner_up_nationality: 'AUS', score: '6-3 3-6 6-3 2-6 9-7' },
  { year: 2001, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Lleyton Hewitt', runner_up: 'Pete Sampras', winner_nationality: 'AUS', runner_up_nationality: 'USA', score: '7-6 6-1 6-1' },
  { year: 2001, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Andre Agassi', runner_up: 'Pete Sampras', winner_nationality: 'USA', runner_up_nationality: 'USA' },
  { year: 2001, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Andre Agassi', runner_up: 'Jan-Michael Gambill', winner_nationality: 'USA', runner_up_nationality: 'USA' },
  { year: 2001, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Gustavo Kuerten', runner_up: 'Franco Squillari', winner_nationality: 'BRA', runner_up_nationality: 'ARG' },
  { year: 2001, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Juan Carlos Ferrero', runner_up: 'Gustavo Kuerten', winner_nationality: 'ESP', runner_up_nationality: 'BRA' },
  { year: 2001, name: 'Hamburg', category: 'Masters 1000', surface: 'Clay', winner: 'Roger Federer', runner_up: 'Marat Safin', winner_nationality: 'SUI', runner_up_nationality: 'RUS' },
  { year: 2001, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Andrei Pavel', runner_up: 'Lleyton Hewitt', winner_nationality: 'ROU', runner_up_nationality: 'AUS' },
  { year: 2001, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Lleyton Hewitt', runner_up: 'Thomas Enqvist', winner_nationality: 'AUS', runner_up_nationality: 'SWE' },
  { year: 2001, name: 'Stuttgart', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Tim Henman', runner_up: 'Andre Agassi', winner_nationality: 'GBR', runner_up_nationality: 'USA' },
  { year: 2001, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Lleyton Hewitt', runner_up: 'Sebastien Grosjean', winner_nationality: 'AUS', runner_up_nationality: 'FRA' },

  // ── 2002 ──────────────────────────────────────────────────────
  { year: 2002, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Thomas Johansson', runner_up: 'Marat Safin', winner_nationality: 'SWE', runner_up_nationality: 'RUS', score: '3-6 6-4 6-4 7-6' },
  { year: 2002, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Albert Costa', runner_up: 'Juan Carlos Ferrero', winner_nationality: 'ESP', runner_up_nationality: 'ESP', score: '6-1 6-0 4-6 6-3' },
  { year: 2002, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Lleyton Hewitt', runner_up: 'David Nalbandian', winner_nationality: 'AUS', runner_up_nationality: 'ARG', score: '6-1 6-3 6-2' },
  { year: 2002, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Pete Sampras', runner_up: 'Andre Agassi', winner_nationality: 'USA', runner_up_nationality: 'USA', score: '6-3 6-4 5-7 6-4' },
  { year: 2002, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Lleyton Hewitt', runner_up: 'Tim Henman', winner_nationality: 'AUS', runner_up_nationality: 'GBR' },
  { year: 2002, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Andre Agassi', runner_up: 'Roger Federer', winner_nationality: 'USA', runner_up_nationality: 'SUI' },
  { year: 2002, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Juan Carlos Ferrero', runner_up: 'Feliciano Lopez', winner_nationality: 'ESP', runner_up_nationality: 'ESP' },
  { year: 2002, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Andre Agassi', runner_up: 'Tommy Haas', winner_nationality: 'USA', runner_up_nationality: 'GER' },
  { year: 2002, name: 'Hamburg', category: 'Masters 1000', surface: 'Clay', winner: 'Marat Safin', runner_up: 'Juan Carlos Ferrero', winner_nationality: 'RUS', runner_up_nationality: 'ESP' },
  { year: 2002, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Lleyton Hewitt', runner_up: 'Carlos Moya', winner_nationality: 'AUS', runner_up_nationality: 'ESP' },
  { year: 2002, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Carlos Moya', runner_up: 'Andre Agassi', winner_nationality: 'ESP', runner_up_nationality: 'USA' },
  { year: 2002, name: 'Madrid', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Marat Safin', runner_up: 'Roger Federer', winner_nationality: 'RUS', runner_up_nationality: 'SUI' },
  { year: 2002, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Marat Safin', runner_up: 'Sebastien Grosjean', winner_nationality: 'RUS', runner_up_nationality: 'FRA' },

  // ── 2003 ──────────────────────────────────────────────────────
  { year: 2003, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Andre Agassi', runner_up: 'Rainer Schuettler', winner_nationality: 'USA', runner_up_nationality: 'GER', score: '6-2 6-2 6-1' },
  { year: 2003, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Juan Carlos Ferrero', runner_up: 'Martin Verkerk', winner_nationality: 'ESP', runner_up_nationality: 'NED', score: '6-1 6-3 6-2' },
  { year: 2003, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Roger Federer', runner_up: 'Mark Philippoussis', winner_nationality: 'SUI', runner_up_nationality: 'AUS', score: '7-6 6-2 7-6' },
  { year: 2003, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Andy Roddick', runner_up: 'Juan Carlos Ferrero', winner_nationality: 'USA', runner_up_nationality: 'ESP', score: '6-3 7-6 6-3' },
  { year: 2003, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Lleyton Hewitt', runner_up: 'Gustavo Kuerten', winner_nationality: 'AUS', runner_up_nationality: 'BRA' },
  { year: 2003, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Andre Agassi', runner_up: 'Carlos Moya', winner_nationality: 'USA', runner_up_nationality: 'ESP' },
  { year: 2003, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Juan Carlos Ferrero', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI' },
  { year: 2003, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Felix Mantilla', runner_up: 'Guillermo Coria', winner_nationality: 'ESP', runner_up_nationality: 'ARG' },
  { year: 2003, name: 'Hamburg', category: 'Masters 1000', surface: 'Clay', winner: 'Roger Federer', runner_up: 'Guillermo Coria', winner_nationality: 'SUI', runner_up_nationality: 'ARG' },
  { year: 2003, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Andy Roddick', runner_up: 'Roger Federer', winner_nationality: 'USA', runner_up_nationality: 'SUI' },
  { year: 2003, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Andy Roddick', runner_up: 'Mardy Fish', winner_nationality: 'USA', runner_up_nationality: 'USA' },
  { year: 2003, name: 'Madrid', category: 'Masters 1000', surface: 'Hard (i)', winner: 'David Nalbandian', runner_up: 'Andre Agassi', winner_nationality: 'ARG', runner_up_nationality: 'USA' },
  { year: 2003, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Marat Safin', runner_up: 'Andre Agassi', winner_nationality: 'RUS', runner_up_nationality: 'USA' },

  // ── 2004 ──────────────────────────────────────────────────────
  { year: 2004, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Marat Safin', winner_nationality: 'SUI', runner_up_nationality: 'RUS', score: '7-6 6-4 6-2' },
  { year: 2004, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Gaston Gaudio', runner_up: 'Guillermo Coria', winner_nationality: 'ARG', runner_up_nationality: 'ARG', score: '0-6 3-6 6-4 6-1 8-6' },
  { year: 2004, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Roger Federer', runner_up: 'Andy Roddick', winner_nationality: 'SUI', runner_up_nationality: 'USA', score: '4-6 7-5 7-6 6-4' },
  { year: 2004, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Lleyton Hewitt', winner_nationality: 'SUI', runner_up_nationality: 'AUS', score: '6-0 7-6 6-0' },
  { year: 2004, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Tim Henman', winner_nationality: 'SUI', runner_up_nationality: 'GBR' },
  { year: 2004, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Andy Roddick', runner_up: 'Lleyton Hewitt', winner_nationality: 'USA', runner_up_nationality: 'AUS' },
  { year: 2004, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Guillermo Coria', winner_nationality: 'ESP', runner_up_nationality: 'ARG' },
  { year: 2004, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Carlos Moya', runner_up: 'Guillermo Coria', winner_nationality: 'ESP', runner_up_nationality: 'ARG' },
  { year: 2004, name: 'Hamburg', category: 'Masters 1000', surface: 'Clay', winner: 'Guillermo Coria', runner_up: 'Guillermo Canas', winner_nationality: 'ARG', runner_up_nationality: 'ARG' },
  { year: 2004, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Andy Roddick', winner_nationality: 'SUI', runner_up_nationality: 'USA' },
  { year: 2004, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Andre Agassi', runner_up: 'Roger Federer', winner_nationality: 'USA', runner_up_nationality: 'SUI' },
  { year: 2004, name: 'Madrid', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Marat Safin', runner_up: 'Andre Agassi', winner_nationality: 'RUS', runner_up_nationality: 'USA' },
  { year: 2004, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Roger Federer', runner_up: 'Marat Safin', winner_nationality: 'SUI', runner_up_nationality: 'RUS' },

  // ── 2005 ──────────────────────────────────────────────────────
  { year: 2005, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Marat Safin', runner_up: 'Lleyton Hewitt', winner_nationality: 'RUS', runner_up_nationality: 'AUS', score: '1-6 6-3 6-4 6-4' },
  { year: 2005, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Mariano Puerta', winner_nationality: 'ESP', runner_up_nationality: 'ARG', score: '6-7 6-3 6-1 7-5' },
  { year: 2005, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Roger Federer', runner_up: 'Andy Roddick', winner_nationality: 'SUI', runner_up_nationality: 'USA', score: '6-2 7-6 6-4' },
  { year: 2005, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Andre Agassi', winner_nationality: 'SUI', runner_up_nationality: 'USA', score: '6-3 2-6 7-6 6-1' },
  { year: 2005, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Rafael Nadal', winner_nationality: 'SUI', runner_up_nationality: 'ESP' },
  { year: 2005, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Rafael Nadal', winner_nationality: 'SUI', runner_up_nationality: 'ESP' },
  { year: 2005, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Guillermo Coria', winner_nationality: 'ESP', runner_up_nationality: 'ARG' },
  { year: 2005, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Guillermo Coria', winner_nationality: 'ESP', runner_up_nationality: 'ARG' },
  { year: 2005, name: 'Hamburg', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Nikolay Davydenko', winner_nationality: 'ESP', runner_up_nationality: 'RUS' },
  { year: 2005, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Rafael Nadal', runner_up: 'Andre Agassi', winner_nationality: 'ESP', runner_up_nationality: 'USA' },
  { year: 2005, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'David Nalbandian', winner_nationality: 'SUI', runner_up_nationality: 'ARG' },
  { year: 2005, name: 'Madrid', category: 'Masters 1000', surface: 'Hard (i)', winner: 'David Nalbandian', runner_up: 'Ivan Ljubicic', winner_nationality: 'ARG', runner_up_nationality: 'CRO' },
  { year: 2005, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Richard Gasquet', runner_up: 'Tomas Berdych', winner_nationality: 'FRA', runner_up_nationality: 'CZE' },

  // ── 2006 ──────────────────────────────────────────────────────
  { year: 2006, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Marco Baghdatis', winner_nationality: 'SUI', runner_up_nationality: 'CYP', score: '5-7 7-5 6-0 6-2' },
  { year: 2006, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI', score: '1-6 6-1 6-4 7-6' },
  { year: 2006, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Roger Federer', runner_up: 'Rafael Nadal', winner_nationality: 'SUI', runner_up_nationality: 'ESP', score: '6-0 7-6 6-7 6-3' },
  { year: 2006, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Andy Roddick', winner_nationality: 'SUI', runner_up_nationality: 'USA', score: '6-2 4-6 7-5 6-1' },
  { year: 2006, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'James Blake', winner_nationality: 'SUI', runner_up_nationality: 'USA' },
  { year: 2006, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Ivan Ljubicic', winner_nationality: 'SUI', runner_up_nationality: 'CRO' },
  { year: 2006, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI' },
  { year: 2006, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI' },
  { year: 2006, name: 'Hamburg', category: 'Masters 1000', surface: 'Clay', winner: 'Roger Federer', runner_up: 'Rafael Nadal', winner_nationality: 'SUI', runner_up_nationality: 'ESP' },
  { year: 2006, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Richard Gasquet', winner_nationality: 'SUI', runner_up_nationality: 'FRA' },
  { year: 2006, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'James Blake', winner_nationality: 'SUI', runner_up_nationality: 'USA' },
  { year: 2006, name: 'Madrid', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Roger Federer', runner_up: 'Rafael Nadal', winner_nationality: 'SUI', runner_up_nationality: 'ESP' },
  { year: 2006, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Nikolay Davydenko', runner_up: 'Jonas Bjorkman', winner_nationality: 'RUS', runner_up_nationality: 'SWE' },

  // ── 2007 ──────────────────────────────────────────────────────
  { year: 2007, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Fernando Gonzalez', winner_nationality: 'SUI', runner_up_nationality: 'CHI', score: '7-6 6-4 6-4' },
  { year: 2007, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI', score: '6-3 4-6 6-3 6-4' },
  { year: 2007, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Roger Federer', runner_up: 'Rafael Nadal', winner_nationality: 'SUI', runner_up_nationality: 'ESP', score: '7-6 4-6 7-6 2-6 6-2' },
  { year: 2007, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Novak Djokovic', winner_nationality: 'SUI', runner_up_nationality: 'SRB', score: '7-6 7-6 6-4' },
  { year: 2007, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Rafael Nadal', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB' },
  { year: 2007, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Guillermo Canas', winner_nationality: 'SRB', runner_up_nationality: 'ARG' },
  { year: 2007, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI' },
  { year: 2007, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Fernando Gonzalez', winner_nationality: 'ESP', runner_up_nationality: 'CHI' },
  { year: 2007, name: 'Hamburg', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI' },
  { year: 2007, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Roger Federer', winner_nationality: 'SRB', runner_up_nationality: 'SUI' },
  { year: 2007, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'James Blake', winner_nationality: 'SUI', runner_up_nationality: 'USA' },
  { year: 2007, name: 'Madrid', category: 'Masters 1000', surface: 'Hard (i)', winner: 'David Nalbandian', runner_up: 'Roger Federer', winner_nationality: 'ARG', runner_up_nationality: 'SUI' },
  { year: 2007, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'David Nalbandian', runner_up: 'Novak Djokovic', winner_nationality: 'ARG', runner_up_nationality: 'SRB' },

  // ── 2008 ──────────────────────────────────────────────────────
  { year: 2008, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Jo-Wilfried Tsonga', winner_nationality: 'SRB', runner_up_nationality: 'FRA', score: '4-6 6-4 6-3 7-6' },
  { year: 2008, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI', score: '6-1 6-3 6-0' },
  { year: 2008, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Rafael Nadal', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI', score: '6-4 6-4 6-7 6-7 9-7' },
  { year: 2008, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Andy Murray', winner_nationality: 'SUI', runner_up_nationality: 'GBR', score: '6-2 7-5 6-2' },
  { year: 2008, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Mardy Fish', winner_nationality: 'SRB', runner_up_nationality: 'USA' },
  { year: 2008, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Nikolay Davydenko', runner_up: 'David Ferrer', winner_nationality: 'RUS', runner_up_nationality: 'ESP' },
  { year: 2008, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI' },
  { year: 2008, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Stanislas Wawrinka', winner_nationality: 'ESP', runner_up_nationality: 'SUI' },
  { year: 2008, name: 'Hamburg', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI' },
  { year: 2008, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Rafael Nadal', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB' },
  { year: 2008, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Andy Murray', runner_up: 'Rafael Nadal', winner_nationality: 'GBR', runner_up_nationality: 'ESP' },
  { year: 2008, name: 'Madrid', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Novak Djokovic', runner_up: 'Gilles Simon', winner_nationality: 'SRB', runner_up_nationality: 'FRA' },
  { year: 2008, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Jo-Wilfried Tsonga', runner_up: 'Gael Monfils', winner_nationality: 'FRA', runner_up_nationality: 'FRA' },

  // ── 2009 ──────────────────────────────────────────────────────
  { year: 2009, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Rafael Nadal', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI', score: '7-5 3-6 7-6 3-6 6-2' },
  { year: 2009, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Roger Federer', runner_up: 'Robin Soderling', winner_nationality: 'SUI', runner_up_nationality: 'SWE', score: '6-1 7-6 6-4' },
  { year: 2009, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Roger Federer', runner_up: 'Andy Roddick', winner_nationality: 'SUI', runner_up_nationality: 'USA', score: '5-7 7-6 7-6 3-6 16-14' },
  { year: 2009, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Juan Martin del Potro', runner_up: 'Roger Federer', winner_nationality: 'ARG', runner_up_nationality: 'SUI', score: '3-6 7-6 4-6 7-6 6-2' },
  { year: 2009, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Rafael Nadal', runner_up: 'Andy Murray', winner_nationality: 'ESP', runner_up_nationality: 'GBR' },
  { year: 2009, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Andy Murray', runner_up: 'Novak Djokovic', winner_nationality: 'GBR', runner_up_nationality: 'SRB' },
  { year: 2009, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB' },
  { year: 2009, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB' },
  { year: 2009, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI' },
  { year: 2009, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Andy Murray', runner_up: 'Rafael Nadal', winner_nationality: 'GBR', runner_up_nationality: 'ESP' },
  { year: 2009, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Novak Djokovic', winner_nationality: 'SUI', runner_up_nationality: 'SRB' },
  { year: 2009, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'Nikolay Davydenko', runner_up: 'Rafael Nadal', winner_nationality: 'RUS', runner_up_nationality: 'ESP' },
  { year: 2009, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Nikolay Davydenko', runner_up: 'Gael Monfils', winner_nationality: 'RUS', runner_up_nationality: 'FRA' },

  // ── 2010 ──────────────────────────────────────────────────────
  { year: 2010, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Andy Murray', winner_nationality: 'SUI', runner_up_nationality: 'GBR', score: '6-3 6-4 7-6' },
  { year: 2010, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Robin Soderling', winner_nationality: 'ESP', runner_up_nationality: 'SWE', score: '6-4 6-2 6-4' },
  { year: 2010, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Rafael Nadal', runner_up: 'Tomas Berdych', winner_nationality: 'ESP', runner_up_nationality: 'CZE', score: '6-3 7-5 6-4' },
  { year: 2010, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Rafael Nadal', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB', score: '6-4 5-7 6-4 6-2' },
  { year: 2010, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Ivan Ljubicic', runner_up: 'Andy Roddick', winner_nationality: 'CRO', runner_up_nationality: 'USA' },
  { year: 2010, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Andy Roddick', runner_up: 'Tomas Berdych', winner_nationality: 'USA', runner_up_nationality: 'CZE' },
  { year: 2010, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Fernando Verdasco', winner_nationality: 'ESP', runner_up_nationality: 'ESP' },
  { year: 2010, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'David Ferrer', winner_nationality: 'ESP', runner_up_nationality: 'ESP' },
  { year: 2010, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI' },
  { year: 2010, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Mardy Fish', winner_nationality: 'SUI', runner_up_nationality: 'USA' },
  { year: 2010, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Mardy Fish', winner_nationality: 'SUI', runner_up_nationality: 'USA' },
  { year: 2010, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'Andy Murray', runner_up: 'Rafael Nadal', winner_nationality: 'GBR', runner_up_nationality: 'ESP' },
  { year: 2010, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Robin Soderling', runner_up: 'Roger Federer', winner_nationality: 'SWE', runner_up_nationality: 'SUI' },

  // ── 2011 ──────────────────────────────────────────────────────
  { year: 2011, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Andy Murray', winner_nationality: 'SRB', runner_up_nationality: 'GBR', score: '6-4 6-2 6-3' },
  { year: 2011, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI', score: '7-5 7-6 5-7 6-1' },
  { year: 2011, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Novak Djokovic', runner_up: 'Rafael Nadal', winner_nationality: 'SRB', runner_up_nationality: 'ESP', score: '6-4 6-1 1-6 6-3' },
  { year: 2011, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Rafael Nadal', winner_nationality: 'SRB', runner_up_nationality: 'ESP', score: '6-2 6-4 6-7 6-1' },
  { year: 2011, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Rafael Nadal', winner_nationality: 'SRB', runner_up_nationality: 'ESP' },
  { year: 2011, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Rafael Nadal', winner_nationality: 'SRB', runner_up_nationality: 'ESP' },
  { year: 2011, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'David Ferrer', winner_nationality: 'ESP', runner_up_nationality: 'ESP' },
  { year: 2011, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Novak Djokovic', runner_up: 'Rafael Nadal', winner_nationality: 'SRB', runner_up_nationality: 'ESP' },
  { year: 2011, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'Novak Djokovic', runner_up: 'Rafael Nadal', winner_nationality: 'SRB', runner_up_nationality: 'ESP' },
  { year: 2011, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Jo-Wilfried Tsonga', winner_nationality: 'SRB', runner_up_nationality: 'FRA' },
  { year: 2011, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Andy Murray', runner_up: 'Novak Djokovic', winner_nationality: 'GBR', runner_up_nationality: 'SRB' },
  { year: 2011, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'Andy Murray', runner_up: 'David Ferrer', winner_nationality: 'GBR', runner_up_nationality: 'ESP' },
  { year: 2011, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Roger Federer', runner_up: 'Jo-Wilfried Tsonga', winner_nationality: 'SUI', runner_up_nationality: 'FRA' },

  // ── 2012 ──────────────────────────────────────────────────────
  { year: 2012, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Rafael Nadal', winner_nationality: 'SRB', runner_up_nationality: 'ESP', score: '5-7 6-4 6-2 6-7 7-5' },
  { year: 2012, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB', score: '6-4 6-3 2-6 7-5' },
  { year: 2012, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Roger Federer', runner_up: 'Andy Murray', winner_nationality: 'SUI', runner_up_nationality: 'GBR', score: '4-6 7-5 6-3 6-4' },
  { year: 2012, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Andy Murray', runner_up: 'Novak Djokovic', winner_nationality: 'GBR', runner_up_nationality: 'SRB', score: '7-6 7-5 2-6 3-6 6-2' },
  { year: 2012, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Rafael Nadal', runner_up: 'Roger Federer', winner_nationality: 'ESP', runner_up_nationality: 'SUI' },
  { year: 2012, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Rafael Nadal', winner_nationality: 'SRB', runner_up_nationality: 'ESP' },
  { year: 2012, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB' },
  { year: 2012, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB' },
  { year: 2012, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'Roger Federer', runner_up: 'Tomas Berdych', winner_nationality: 'SUI', runner_up_nationality: 'CZE' },
  { year: 2012, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Richard Gasquet', winner_nationality: 'SRB', runner_up_nationality: 'FRA' },
  { year: 2012, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Novak Djokovic', winner_nationality: 'SUI', runner_up_nationality: 'SRB' },
  { year: 2012, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'Andy Murray', runner_up: 'Novak Djokovic', winner_nationality: 'GBR', runner_up_nationality: 'SRB' },
  { year: 2012, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Novak Djokovic', runner_up: 'Roger Federer', winner_nationality: 'SRB', runner_up_nationality: 'SUI' },

  // ── 2013 ──────────────────────────────────────────────────────
  { year: 2013, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Andy Murray', winner_nationality: 'SRB', runner_up_nationality: 'GBR', score: '6-7 7-6 6-3 6-2' },
  { year: 2013, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'David Ferrer', winner_nationality: 'ESP', runner_up_nationality: 'ESP', score: '6-3 6-2 6-3' },
  { year: 2013, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Andy Murray', runner_up: 'Novak Djokovic', winner_nationality: 'GBR', runner_up_nationality: 'SRB', score: '6-4 7-5 6-4' },
  { year: 2013, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Rafael Nadal', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB', score: '6-2 3-6 6-4 6-1' },
  { year: 2013, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Rafael Nadal', runner_up: 'Juan Martin del Potro', winner_nationality: 'ESP', runner_up_nationality: 'ARG' },
  { year: 2013, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Andy Murray', runner_up: 'David Ferrer', winner_nationality: 'GBR', runner_up_nationality: 'ESP' },
  { year: 2013, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Tomas Berdych', winner_nationality: 'ESP', runner_up_nationality: 'CZE' },
  { year: 2013, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB' },
  { year: 2013, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Stanislas Wawrinka', winner_nationality: 'ESP', runner_up_nationality: 'SUI' },
  { year: 2013, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Rafael Nadal', runner_up: 'Milos Raonic', winner_nationality: 'ESP', runner_up_nationality: 'CAN' },
  { year: 2013, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Rafael Nadal', runner_up: 'John Isner', winner_nationality: 'ESP', runner_up_nationality: 'USA' },
  { year: 2013, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Juan Martin del Potro', winner_nationality: 'SRB', runner_up_nationality: 'ARG' },
  { year: 2013, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Novak Djokovic', runner_up: 'Jo-Wilfried Tsonga', winner_nationality: 'SRB', runner_up_nationality: 'FRA' },

  // ── 2014 ──────────────────────────────────────────────────────
  { year: 2014, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Stanislas Wawrinka', runner_up: 'Rafael Nadal', winner_nationality: 'SUI', runner_up_nationality: 'ESP', score: '6-3 6-2 3-6 6-3' },
  { year: 2014, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB', score: '3-6 7-5 6-2 6-4' },
  { year: 2014, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Novak Djokovic', runner_up: 'Roger Federer', winner_nationality: 'SRB', runner_up_nationality: 'SUI', score: '6-7 6-4 7-6 5-7 6-4' },
  { year: 2014, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Marin Cilic', runner_up: 'Kei Nishikori', winner_nationality: 'CRO', runner_up_nationality: 'JPN', score: '6-3 6-3 6-3' },
  { year: 2014, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Roger Federer', winner_nationality: 'SRB', runner_up_nationality: 'SUI' },
  { year: 2014, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Rafael Nadal', winner_nationality: 'SRB', runner_up_nationality: 'ESP' },
  { year: 2014, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB' },
  { year: 2014, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Novak Djokovic', runner_up: 'Rafael Nadal', winner_nationality: 'SRB', runner_up_nationality: 'ESP' },
  { year: 2014, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Kei Nishikori', winner_nationality: 'ESP', runner_up_nationality: 'JPN' },
  { year: 2014, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Jo-Wilfried Tsonga', runner_up: 'Roger Federer', winner_nationality: 'FRA', runner_up_nationality: 'SUI' },
  { year: 2014, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'David Ferrer', winner_nationality: 'SUI', runner_up_nationality: 'ESP' },
  { year: 2014, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Gael Monfils', winner_nationality: 'SRB', runner_up_nationality: 'FRA' },
  { year: 2014, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Novak Djokovic', runner_up: 'Milos Raonic', winner_nationality: 'SRB', runner_up_nationality: 'CAN' },

  // ── 2015 ──────────────────────────────────────────────────────
  { year: 2015, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Andy Murray', winner_nationality: 'SRB', runner_up_nationality: 'GBR', score: '7-6 6-7 6-3 6-0' },
  { year: 2015, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Stanislas Wawrinka', runner_up: 'Novak Djokovic', winner_nationality: 'SUI', runner_up_nationality: 'SRB', score: '4-6 6-4 6-3 6-4' },
  { year: 2015, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Novak Djokovic', runner_up: 'Roger Federer', winner_nationality: 'SRB', runner_up_nationality: 'SUI', score: '7-6 6-7 6-4 6-3' },
  { year: 2015, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Roger Federer', winner_nationality: 'SRB', runner_up_nationality: 'SUI', score: '6-4 5-7 6-4 6-4' },
  { year: 2015, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Roger Federer', winner_nationality: 'SRB', runner_up_nationality: 'SUI' },
  { year: 2015, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Andy Murray', winner_nationality: 'SRB', runner_up_nationality: 'GBR' },
  { year: 2015, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Novak Djokovic', runner_up: 'Tomas Berdych', winner_nationality: 'SRB', runner_up_nationality: 'CZE' },
  { year: 2015, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Novak Djokovic', runner_up: 'Roger Federer', winner_nationality: 'SRB', runner_up_nationality: 'SUI' },
  { year: 2015, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'Andy Murray', runner_up: 'Rafael Nadal', winner_nationality: 'GBR', runner_up_nationality: 'ESP' },
  { year: 2015, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Roger Federer', winner_nationality: 'SRB', runner_up_nationality: 'SUI' },
  { year: 2015, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Novak Djokovic', winner_nationality: 'SUI', runner_up_nationality: 'SRB' },
  { year: 2015, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Jo-Wilfried Tsonga', winner_nationality: 'SRB', runner_up_nationality: 'FRA' },
  { year: 2015, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Novak Djokovic', runner_up: 'Andy Murray', winner_nationality: 'SRB', runner_up_nationality: 'GBR' },

  // ── 2016 ──────────────────────────────────────────────────────
  { year: 2016, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Andy Murray', winner_nationality: 'SRB', runner_up_nationality: 'GBR', score: '6-1 7-5 7-6' },
  { year: 2016, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Novak Djokovic', runner_up: 'Andy Murray', winner_nationality: 'SRB', runner_up_nationality: 'GBR', score: '3-6 6-1 6-2 6-4' },
  { year: 2016, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Andy Murray', runner_up: 'Milos Raonic', winner_nationality: 'GBR', runner_up_nationality: 'CAN', score: '6-4 7-6 7-6' },
  { year: 2016, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Stanislas Wawrinka', runner_up: 'Novak Djokovic', winner_nationality: 'SUI', runner_up_nationality: 'SRB', score: '6-7 6-4 7-5 6-3' },
  { year: 2016, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Milos Raonic', winner_nationality: 'SRB', runner_up_nationality: 'CAN' },
  { year: 2016, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Kei Nishikori', winner_nationality: 'SRB', runner_up_nationality: 'JPN' },
  { year: 2016, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Gael Monfils', winner_nationality: 'ESP', runner_up_nationality: 'FRA' },
  { year: 2016, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Novak Djokovic', runner_up: 'Alexander Zverev', winner_nationality: 'SRB', runner_up_nationality: 'GER' },
  { year: 2016, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'Andy Murray', runner_up: 'Novak Djokovic', winner_nationality: 'GBR', runner_up_nationality: 'SRB' },
  { year: 2016, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Kei Nishikori', winner_nationality: 'SRB', runner_up_nationality: 'JPN' },
  { year: 2016, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Andy Murray', runner_up: 'Marin Cilic', winner_nationality: 'GBR', runner_up_nationality: 'CRO' },
  { year: 2016, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'Andy Murray', runner_up: 'Roberto Bautista Agut', winner_nationality: 'GBR', runner_up_nationality: 'ESP' },
  { year: 2016, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Andy Murray', runner_up: 'John Isner', winner_nationality: 'GBR', runner_up_nationality: 'USA' },

  // ── 2017 ──────────────────────────────────────────────────────
  { year: 2017, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Rafael Nadal', winner_nationality: 'SUI', runner_up_nationality: 'ESP', score: '6-4 3-6 6-1 3-6 6-3' },
  { year: 2017, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Stanislas Wawrinka', winner_nationality: 'ESP', runner_up_nationality: 'SUI', score: '6-2 6-3 6-1' },
  { year: 2017, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Roger Federer', runner_up: 'Marin Cilic', winner_nationality: 'SUI', runner_up_nationality: 'CRO', score: '6-3 6-1 6-4' },
  { year: 2017, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Rafael Nadal', runner_up: 'Kevin Anderson', winner_nationality: 'ESP', runner_up_nationality: 'RSA', score: '6-3 6-3 6-4' },
  { year: 2017, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Stan Wawrinka', winner_nationality: 'SUI', runner_up_nationality: 'SUI' },
  { year: 2017, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Rafael Nadal', winner_nationality: 'SUI', runner_up_nationality: 'ESP' },
  { year: 2017, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Albert Ramos-Vinolas', winner_nationality: 'ESP', runner_up_nationality: 'ESP' },
  { year: 2017, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Alexander Zverev', runner_up: 'Novak Djokovic', winner_nationality: 'GER', runner_up_nationality: 'SRB' },
  { year: 2017, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Dominic Thiem', winner_nationality: 'ESP', runner_up_nationality: 'AUT' },
  { year: 2017, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Alexander Zverev', runner_up: 'Roger Federer', winner_nationality: 'GER', runner_up_nationality: 'SUI' },
  { year: 2017, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Grigor Dimitrov', runner_up: 'Nick Kyrgios', winner_nationality: 'BUL', runner_up_nationality: 'AUS' },
  { year: 2017, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Rafael Nadal', winner_nationality: 'SUI', runner_up_nationality: 'ESP' },
  { year: 2017, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Jack Sock', runner_up: 'Filip Krajinovic', winner_nationality: 'USA', runner_up_nationality: 'SRB' },

  // ── 2018 ──────────────────────────────────────────────────────
  { year: 2018, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Roger Federer', runner_up: 'Marin Cilic', winner_nationality: 'SUI', runner_up_nationality: 'CRO', score: '6-2 6-7 6-3 3-6 6-1' },
  { year: 2018, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Dominic Thiem', winner_nationality: 'ESP', runner_up_nationality: 'AUT', score: '6-4 6-3 6-2' },
  { year: 2018, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Novak Djokovic', runner_up: 'Kevin Anderson', winner_nationality: 'SRB', runner_up_nationality: 'RSA', score: '6-2 6-2 7-6' },
  { year: 2018, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Juan Martin del Potro', winner_nationality: 'SRB', runner_up_nationality: 'ARG', score: '6-3 7-6 6-3' },
  { year: 2018, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Juan Martin del Potro', runner_up: 'Roger Federer', winner_nationality: 'ARG', runner_up_nationality: 'SUI' },
  { year: 2018, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'John Isner', runner_up: 'Alexander Zverev', winner_nationality: 'USA', runner_up_nationality: 'GER' },
  { year: 2018, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Kei Nishikori', winner_nationality: 'ESP', runner_up_nationality: 'JPN' },
  { year: 2018, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Alexander Zverev', winner_nationality: 'ESP', runner_up_nationality: 'GER' },
  { year: 2018, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'Alexander Zverev', runner_up: 'Dominic Thiem', winner_nationality: 'GER', runner_up_nationality: 'AUT' },
  { year: 2018, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Rafael Nadal', runner_up: 'Stefanos Tsitsipas', winner_nationality: 'ESP', runner_up_nationality: 'GRE' },
  { year: 2018, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Roger Federer', winner_nationality: 'SRB', runner_up_nationality: 'SUI' },
  { year: 2018, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Borna Coric', winner_nationality: 'SRB', runner_up_nationality: 'CRO' },
  { year: 2018, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Karen Khachanov', runner_up: 'Novak Djokovic', winner_nationality: 'RUS', runner_up_nationality: 'SRB' },

  // ── 2019 ──────────────────────────────────────────────────────
  { year: 2019, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Rafael Nadal', winner_nationality: 'SRB', runner_up_nationality: 'ESP', score: '6-3 6-2 6-3' },
  { year: 2019, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Dominic Thiem', winner_nationality: 'ESP', runner_up_nationality: 'AUT', score: '6-3 5-7 6-1 6-1' },
  { year: 2019, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Novak Djokovic', runner_up: 'Roger Federer', winner_nationality: 'SRB', runner_up_nationality: 'SUI', score: '7-6 1-6 7-6 4-6 13-12' },
  { year: 2019, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Rafael Nadal', runner_up: 'Daniil Medvedev', winner_nationality: 'ESP', runner_up_nationality: 'RUS', score: '7-5 6-3 5-7 4-6 6-4' },
  { year: 2019, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Dominic Thiem', runner_up: 'Roger Federer', winner_nationality: 'AUT', runner_up_nationality: 'SUI' },
  { year: 2019, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Roger Federer', runner_up: 'John Isner', winner_nationality: 'SUI', runner_up_nationality: 'USA' },
  { year: 2019, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Fabio Fognini', runner_up: 'Dusan Lajovic', winner_nationality: 'ITA', runner_up_nationality: 'SRB' },
  { year: 2019, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB' },
  { year: 2019, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'Novak Djokovic', runner_up: 'Stefanos Tsitsipas', winner_nationality: 'SRB', runner_up_nationality: 'GRE' },
  { year: 2019, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Daniil Medvedev', runner_up: 'Gael Monfils', winner_nationality: 'RUS', runner_up_nationality: 'FRA' },
  { year: 2019, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Daniil Medvedev', runner_up: 'David Goffin', winner_nationality: 'RUS', runner_up_nationality: 'BEL' },
  { year: 2019, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Daniil Medvedev', winner_nationality: 'SRB', runner_up_nationality: 'RUS' },
  { year: 2019, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Novak Djokovic', runner_up: 'Denis Shapovalov', winner_nationality: 'SRB', runner_up_nationality: 'CAN' },

  // ── 2020 ──────────────────────────────────────────────────────
  { year: 2020, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Dominic Thiem', winner_nationality: 'SRB', runner_up_nationality: 'AUT', score: '6-4 4-6 2-6 6-3 6-4' },
  { year: 2020, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB', score: '6-0 6-2 7-5' },
  { year: 2020, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'N/A (cancelled)', runner_up: 'N/A', winner_nationality: '', runner_up_nationality: '', score: 'COVID-19' },
  { year: 2020, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Dominic Thiem', runner_up: 'Alexander Zverev', winner_nationality: 'AUT', runner_up_nationality: 'GER', score: '2-6 4-6 6-4 6-3 7-6' },
  { year: 2020, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'N/A (cancelled)', runner_up: 'N/A', winner_nationality: '', runner_up_nationality: '', score: 'COVID-19' },
  { year: 2020, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'N/A (cancelled)', runner_up: 'N/A', winner_nationality: '', runner_up_nationality: '', score: 'COVID-19' },
  { year: 2020, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'N/A (cancelled)', runner_up: 'N/A', winner_nationality: '', runner_up_nationality: '', score: 'COVID-19' },
  { year: 2020, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB' },
  { year: 2020, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'N/A (cancelled)', runner_up: 'N/A', winner_nationality: '', runner_up_nationality: '', score: 'COVID-19' },
  { year: 2020, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'N/A (cancelled)', runner_up: 'N/A', winner_nationality: '', runner_up_nationality: '', score: 'COVID-19' },
  { year: 2020, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Milos Raonic', winner_nationality: 'SRB', runner_up_nationality: 'CAN' },
  { year: 2020, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'N/A (cancelled)', runner_up: 'N/A', winner_nationality: '', runner_up_nationality: '', score: 'COVID-19' },
  { year: 2020, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Daniil Medvedev', runner_up: 'Alexander Zverev', winner_nationality: 'RUS', runner_up_nationality: 'GER' },

  // ── 2021 ──────────────────────────────────────────────────────
  { year: 2021, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Daniil Medvedev', winner_nationality: 'SRB', runner_up_nationality: 'RUS', score: '7-5 6-2 6-2' },
  { year: 2021, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Novak Djokovic', runner_up: 'Stefanos Tsitsipas', winner_nationality: 'SRB', runner_up_nationality: 'GRE', score: '6-7 2-6 6-3 6-2 6-4' },
  { year: 2021, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Novak Djokovic', runner_up: 'Matteo Berrettini', winner_nationality: 'SRB', runner_up_nationality: 'ITA', score: '6-7 6-4 6-4 6-3' },
  { year: 2021, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Daniil Medvedev', runner_up: 'Novak Djokovic', winner_nationality: 'RUS', runner_up_nationality: 'SRB', score: '6-4 6-4 6-4' },
  { year: 2021, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Cameron Norrie', runner_up: 'Nikoloz Basilashvili', winner_nationality: 'GBR', runner_up_nationality: 'GEO' },
  { year: 2021, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Hubert Hurkacz', runner_up: 'Jannik Sinner', winner_nationality: 'POL', runner_up_nationality: 'ITA' },
  { year: 2021, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Stefanos Tsitsipas', runner_up: 'Andrey Rublev', winner_nationality: 'GRE', runner_up_nationality: 'RUS' },
  { year: 2021, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Lorenzo Sonego', winner_nationality: 'ESP', runner_up_nationality: 'ITA' },
  { year: 2021, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'Alexander Zverev', runner_up: 'Matteo Berrettini', winner_nationality: 'GER', runner_up_nationality: 'ITA' },
  { year: 2021, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Daniil Medvedev', runner_up: 'Andrey Rublev', winner_nationality: 'RUS', runner_up_nationality: 'RUS' },
  { year: 2021, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Alexander Zverev', runner_up: 'Andrey Rublev', winner_nationality: 'GER', runner_up_nationality: 'RUS' },
  { year: 2021, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'N/A (cancelled)', runner_up: 'N/A', winner_nationality: '', runner_up_nationality: '' },
  { year: 2021, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Novak Djokovic', runner_up: 'Daniil Medvedev', winner_nationality: 'SRB', runner_up_nationality: 'RUS' },

  // ── 2022 ──────────────────────────────────────────────────────
  { year: 2022, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Rafael Nadal', runner_up: 'Daniil Medvedev', winner_nationality: 'ESP', runner_up_nationality: 'RUS', score: '2-6 6-7 6-4 6-4 7-5' },
  { year: 2022, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Rafael Nadal', runner_up: 'Casper Ruud', winner_nationality: 'ESP', runner_up_nationality: 'NOR', score: '6-3 6-3 6-0' },
  { year: 2022, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Novak Djokovic', runner_up: 'Nick Kyrgios', winner_nationality: 'SRB', runner_up_nationality: 'AUS', score: '4-6 6-3 6-4 7-6' },
  { year: 2022, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Carlos Alcaraz', runner_up: 'Casper Ruud', winner_nationality: 'ESP', runner_up_nationality: 'NOR', score: '6-4 2-6 7-6 6-3' },
  { year: 2022, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Taylor Fritz', runner_up: 'Rafael Nadal', winner_nationality: 'USA', runner_up_nationality: 'ESP' },
  { year: 2022, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Carlos Alcaraz', runner_up: 'Casper Ruud', winner_nationality: 'ESP', runner_up_nationality: 'NOR' },
  { year: 2022, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Stefanos Tsitsipas', runner_up: 'Alejandro Davidovich Fokina', winner_nationality: 'GRE', runner_up_nationality: 'ESP' },
  { year: 2022, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Novak Djokovic', runner_up: 'Stefanos Tsitsipas', winner_nationality: 'SRB', runner_up_nationality: 'GRE' },
  { year: 2022, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'Carlos Alcaraz', runner_up: 'Rafael Nadal', winner_nationality: 'ESP', runner_up_nationality: 'ESP' },
  { year: 2022, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Pablo Carreno Busta', runner_up: 'Hubert Hurkacz', winner_nationality: 'ESP', runner_up_nationality: 'POL' },
  { year: 2022, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Stefanos Tsitsipas', runner_up: 'Borna Coric', winner_nationality: 'GRE', runner_up_nationality: 'CRO' },
  { year: 2022, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'N/A (cancelled)', runner_up: 'N/A', winner_nationality: '', runner_up_nationality: '' },
  { year: 2022, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Holger Rune', runner_up: 'Novak Djokovic', winner_nationality: 'DEN', runner_up_nationality: 'SRB' },

  // ── 2023 ──────────────────────────────────────────────────────
  { year: 2023, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Stefanos Tsitsipas', winner_nationality: 'SRB', runner_up_nationality: 'GRE', score: '6-3 7-6 7-6' },
  { year: 2023, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Novak Djokovic', runner_up: 'Casper Ruud', winner_nationality: 'SRB', runner_up_nationality: 'NOR', score: '7-6 6-3 7-5' },
  { year: 2023, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Carlos Alcaraz', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB', score: '1-6 7-6 6-1 3-6 6-4' },
  { year: 2023, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Daniil Medvedev', winner_nationality: 'SRB', runner_up_nationality: 'RUS', score: '6-3 7-6 6-3' },
  { year: 2023, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Carlos Alcaraz', runner_up: 'Daniil Medvedev', winner_nationality: 'ESP', runner_up_nationality: 'RUS' },
  { year: 2023, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Carlos Alcaraz', runner_up: 'Daniil Medvedev', winner_nationality: 'ESP', runner_up_nationality: 'RUS' },
  { year: 2023, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Andrey Rublev', runner_up: 'Holger Rune', winner_nationality: 'RUS', runner_up_nationality: 'DEN' },
  { year: 2023, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Daniil Medvedev', runner_up: 'Holger Rune', winner_nationality: 'RUS', runner_up_nationality: 'DEN' },
  { year: 2023, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'Carlos Alcaraz', runner_up: 'Jan-Lennard Struff', winner_nationality: 'ESP', runner_up_nationality: 'GER' },
  { year: 2023, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Carlos Alcaraz', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB' },
  { year: 2023, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Carlos Alcaraz', winner_nationality: 'SRB', runner_up_nationality: 'ESP' },
  { year: 2023, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'Carlos Alcaraz', runner_up: 'Alexander Zverev', winner_nationality: 'ESP', runner_up_nationality: 'GER' },
  { year: 2023, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Novak Djokovic', runner_up: 'Grigor Dimitrov', winner_nationality: 'SRB', runner_up_nationality: 'BUL' },

  // ── 2024 ──────────────────────────────────────────────────────
  { year: 2024, name: 'Australian Open', category: 'Grand Slam', surface: 'Hard', winner: 'Jannik Sinner', runner_up: 'Daniil Medvedev', winner_nationality: 'ITA', runner_up_nationality: 'RUS', score: '3-6 3-6 6-4 6-4 6-3' },
  { year: 2024, name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', winner: 'Carlos Alcaraz', runner_up: 'Alexander Zverev', winner_nationality: 'ESP', runner_up_nationality: 'GER', score: '6-3 2-6 5-7 6-1 6-2' },
  { year: 2024, name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', winner: 'Carlos Alcaraz', runner_up: 'Novak Djokovic', winner_nationality: 'ESP', runner_up_nationality: 'SRB', score: '6-2 6-2 7-6' },
  { year: 2024, name: 'US Open', category: 'Grand Slam', surface: 'Hard', winner: 'Jannik Sinner', runner_up: 'Taylor Fritz', winner_nationality: 'ITA', runner_up_nationality: 'USA', score: '6-3 6-4 7-5' },
  { year: 2024, name: 'Indian Wells', category: 'Masters 1000', surface: 'Hard', winner: 'Carlos Alcaraz', runner_up: 'Daniil Medvedev', winner_nationality: 'ESP', runner_up_nationality: 'RUS' },
  { year: 2024, name: 'Miami', category: 'Masters 1000', surface: 'Hard', winner: 'Jannik Sinner', runner_up: 'Grigor Dimitrov', winner_nationality: 'ITA', runner_up_nationality: 'BUL' },
  { year: 2024, name: 'Monte Carlo', category: 'Masters 1000', surface: 'Clay', winner: 'Stefanos Tsitsipas', runner_up: 'Casper Ruud', winner_nationality: 'GRE', runner_up_nationality: 'NOR' },
  { year: 2024, name: 'Rome', category: 'Masters 1000', surface: 'Clay', winner: 'Alexander Zverev', runner_up: 'Nicolas Jarry', winner_nationality: 'GER', runner_up_nationality: 'CHI' },
  { year: 2024, name: 'Madrid', category: 'Masters 1000', surface: 'Clay', winner: 'Andrey Rublev', runner_up: 'Felix Auger-Aliassime', winner_nationality: 'RUS', runner_up_nationality: 'CAN' },
  { year: 2024, name: 'Canada', category: 'Masters 1000', surface: 'Hard', winner: 'Jannik Sinner', runner_up: 'Andrey Rublev', winner_nationality: 'ITA', runner_up_nationality: 'RUS' },
  { year: 2024, name: 'Cincinnati', category: 'Masters 1000', surface: 'Hard', winner: 'Jannik Sinner', runner_up: 'Frances Tiafoe', winner_nationality: 'ITA', runner_up_nationality: 'USA' },
  { year: 2024, name: 'Shanghai', category: 'Masters 1000', surface: 'Hard', winner: 'Novak Djokovic', runner_up: 'Tomas Machac', winner_nationality: 'SRB', runner_up_nationality: 'CZE' },
  { year: 2024, name: 'Paris', category: 'Masters 1000', surface: 'Hard (i)', winner: 'Carlos Alcaraz', runner_up: 'Ugo Humbert', winner_nationality: 'ESP', runner_up_nationality: 'FRA' },
];
